/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'
import { Route as AppMembersRouteImport } from './routes/_app/members'
import { Route as AppEntriesIndexRouteImport } from './routes/_app/entries.index'
import { Route as AppEntriesEntryIdRouteImport } from './routes/_app/entries.$entryId'
import { Route as AppEntriesNewRouteImport } from './routes/_app/entries.new'
import { Route as AppReportsBalanceSheetRouteImport } from './routes/_app/reports.balance-sheet'
import { Route as AppReportsProfitAndLossRouteImport } from './routes/_app/reports.profit-and-loss'
import { Route as AppReportsTrialBalanceRouteImport } from './routes/_app/reports.trial-balance'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiV1AccountsRouteImport } from './routes/api/v1/accounts'
import { Route as ApiV1ContactsRouteImport } from './routes/api/v1/contacts'
import { Route as ApiV1FiscalYearsRouteImport } from './routes/api/v1/fiscal-years'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1JournalEntriesRouteImport } from './routes/api/v1/journal-entries'
import { Route as ApiV1MembersRouteImport } from './routes/api/v1/members'
import { Route as ApiV1SalesInvoicesRouteImport } from './routes/api/v1/sales-invoices'
import { Route as ApiV1TaxCodesRouteImport } from './routes/api/v1/tax-codes'
import { Route as ApiV1EntitiesEntityIdRouteImport } from './routes/api/v1/entities.$entityId'
import { Route as ApiV1ExportsAuditFileRouteImport } from './routes/api/v1/exports.audit-file'
import { Route as ApiV1FiscalYearsCloseRouteImport } from './routes/api/v1/fiscal-years.close'
import { Route as ApiV1ImportsAuditFileRouteImport } from './routes/api/v1/imports.audit-file'
import { Route as ApiV1JournalEntriesEntryIdRouteImport } from './routes/api/v1/journal-entries.$entryId'
import { Route as ApiV1LedgerChainVerificationRouteImport } from './routes/api/v1/ledger.chain-verification'
import { Route as ApiV1MembersMemberIdRouteImport } from './routes/api/v1/members.$memberId'
import { Route as ApiV1ReportsBalanceSheetRouteImport } from './routes/api/v1/reports.balance-sheet'
import { Route as ApiV1ReportsOverdueInvoicesRouteImport } from './routes/api/v1/reports.overdue-invoices'
import { Route as ApiV1ReportsProfitAndLossRouteImport } from './routes/api/v1/reports.profit-and-loss'
import { Route as ApiV1ReportsTrialBalanceRouteImport } from './routes/api/v1/reports.trial-balance'
import { Route as ApiV1RgsCoverageRouteImport } from './routes/api/v1/rgs.coverage'
import { Route as ApiV1RgsMappingsRouteImport } from './routes/api/v1/rgs.mappings'
import { Route as ApiV1RgsUpgradePreviewRouteImport } from './routes/api/v1/rgs.upgrade-preview'
import { Route as ApiV1SalesInvoicesInvoiceIdRouteImport } from './routes/api/v1/sales-invoices.$invoiceId'
import { Route as ApiV1SetupChartsRouteImport } from './routes/api/v1/setup.charts'
import { Route as ApiV1JournalEntriesEntryIdReversalRouteImport } from './routes/api/v1/journal-entries.$entryId.reversal'
import { Route as ApiV1SalesInvoicesInvoiceIdIssueRouteImport } from './routes/api/v1/sales-invoices.$invoiceId.issue'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppEntriesIndexRoute = AppEntriesIndexRouteImport.update({
  id: '/entries/',
  path: '/entries/',
  getParentRoute: () => AppRoute,
} as any)
const AppEntriesEntryIdRoute = AppEntriesEntryIdRouteImport.update({
  id: '/entries/$entryId',
  path: '/entries/$entryId',
  getParentRoute: () => AppRoute,
} as any)
const AppEntriesNewRoute = AppEntriesNewRouteImport.update({
  id: '/entries/new',
  path: '/entries/new',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsBalanceSheetRoute = AppReportsBalanceSheetRouteImport.update({
  id: '/reports/balance-sheet',
  path: '/reports/balance-sheet',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsProfitAndLossRoute = AppReportsProfitAndLossRouteImport.update({
  id: '/reports/profit-and-loss',
  path: '/reports/profit-and-loss',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsTrialBalanceRoute = AppReportsTrialBalanceRouteImport.update({
  id: '/reports/trial-balance',
  path: '/reports/trial-balance',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AccountsRoute = ApiV1AccountsRouteImport.update({
  id: '/api/v1/accounts',
  path: '/api/v1/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ContactsRoute = ApiV1ContactsRouteImport.update({
  id: '/api/v1/contacts',
  path: '/api/v1/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FiscalYearsRoute = ApiV1FiscalYearsRouteImport.update({
  id: '/api/v1/fiscal-years',
  path: '/api/v1/fiscal-years',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JournalEntriesRoute = ApiV1JournalEntriesRouteImport.update({
  id: '/api/v1/journal-entries',
  path: '/api/v1/journal-entries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MembersRoute = ApiV1MembersRouteImport.update({
  id: '/api/v1/members',
  path: '/api/v1/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SalesInvoicesRoute = ApiV1SalesInvoicesRouteImport.update({
  id: '/api/v1/sales-invoices',
  path: '/api/v1/sales-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TaxCodesRoute = ApiV1TaxCodesRouteImport.update({
  id: '/api/v1/tax-codes',
  path: '/api/v1/tax-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EntitiesEntityIdRoute = ApiV1EntitiesEntityIdRouteImport.update({
  id: '/api/v1/entities/$entityId',
  path: '/api/v1/entities/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExportsAuditFileRoute = ApiV1ExportsAuditFileRouteImport.update({
  id: '/api/v1/exports/audit-file',
  path: '/api/v1/exports/audit-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FiscalYearsCloseRoute = ApiV1FiscalYearsCloseRouteImport.update({
  id: '/close',
  path: '/close',
  getParentRoute: () => ApiV1FiscalYearsRoute,
} as any)
const ApiV1ImportsAuditFileRoute = ApiV1ImportsAuditFileRouteImport.update({
  id: '/api/v1/imports/audit-file',
  path: '/api/v1/imports/audit-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JournalEntriesEntryIdRoute =
  ApiV1JournalEntriesEntryIdRouteImport.update({
    id: '/$entryId',
    path: '/$entryId',
    getParentRoute: () => ApiV1JournalEntriesRoute,
  } as any)
const ApiV1LedgerChainVerificationRoute =
  ApiV1LedgerChainVerificationRouteImport.update({
    id: '/api/v1/ledger/chain-verification',
    path: '/api/v1/ledger/chain-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1MembersMemberIdRoute = ApiV1MembersMemberIdRouteImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => ApiV1MembersRoute,
} as any)
const ApiV1ReportsBalanceSheetRoute =
  ApiV1ReportsBalanceSheetRouteImport.update({
    id: '/api/v1/reports/balance-sheet',
    path: '/api/v1/reports/balance-sheet',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ReportsOverdueInvoicesRoute =
  ApiV1ReportsOverdueInvoicesRouteImport.update({
    id: '/api/v1/reports/overdue-invoices',
    path: '/api/v1/reports/overdue-invoices',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ReportsProfitAndLossRoute =
  ApiV1ReportsProfitAndLossRouteImport.update({
    id: '/api/v1/reports/profit-and-loss',
    path: '/api/v1/reports/profit-and-loss',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ReportsTrialBalanceRoute =
  ApiV1ReportsTrialBalanceRouteImport.update({
    id: '/api/v1/reports/trial-balance',
    path: '/api/v1/reports/trial-balance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1RgsCoverageRoute = ApiV1RgsCoverageRouteImport.update({
  id: '/api/v1/rgs/coverage',
  path: '/api/v1/rgs/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RgsMappingsRoute = ApiV1RgsMappingsRouteImport.update({
  id: '/api/v1/rgs/mappings',
  path: '/api/v1/rgs/mappings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RgsUpgradePreviewRoute = ApiV1RgsUpgradePreviewRouteImport.update({
  id: '/api/v1/rgs/upgrade-preview',
  path: '/api/v1/rgs/upgrade-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SalesInvoicesInvoiceIdRoute =
  ApiV1SalesInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => ApiV1SalesInvoicesRoute,
  } as any)
const ApiV1SetupChartsRoute = ApiV1SetupChartsRouteImport.update({
  id: '/api/v1/setup/charts',
  path: '/api/v1/setup/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JournalEntriesEntryIdReversalRoute =
  ApiV1JournalEntriesEntryIdReversalRouteImport.update({
    id: '/reversal',
    path: '/reversal',
    getParentRoute: () => ApiV1JournalEntriesEntryIdRoute,
  } as any)
const ApiV1SalesInvoicesInvoiceIdIssueRoute =
  ApiV1SalesInvoicesInvoiceIdIssueRouteImport.update({
    id: '/issue',
    path: '/issue',
    getParentRoute: () => ApiV1SalesInvoicesInvoiceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/accounts': typeof AppAccountsRoute
  '/members': typeof AppMembersRoute
  '/entries/$entryId': typeof AppEntriesEntryIdRoute
  '/entries/new': typeof AppEntriesNewRoute
  '/reports/balance-sheet': typeof AppReportsBalanceSheetRoute
  '/reports/profit-and-loss': typeof AppReportsProfitAndLossRoute
  '/reports/trial-balance': typeof AppReportsTrialBalanceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/accounts': typeof ApiV1AccountsRoute
  '/api/v1/contacts': typeof ApiV1ContactsRoute
  '/api/v1/fiscal-years': typeof ApiV1FiscalYearsRouteWithChildren
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/journal-entries': typeof ApiV1JournalEntriesRouteWithChildren
  '/api/v1/members': typeof ApiV1MembersRouteWithChildren
  '/api/v1/sales-invoices': typeof ApiV1SalesInvoicesRouteWithChildren
  '/api/v1/tax-codes': typeof ApiV1TaxCodesRoute
  '/entries/': typeof AppEntriesIndexRoute
  '/api/v1/entities/$entityId': typeof ApiV1EntitiesEntityIdRoute
  '/api/v1/exports/audit-file': typeof ApiV1ExportsAuditFileRoute
  '/api/v1/fiscal-years/close': typeof ApiV1FiscalYearsCloseRoute
  '/api/v1/imports/audit-file': typeof ApiV1ImportsAuditFileRoute
  '/api/v1/journal-entries/$entryId': typeof ApiV1JournalEntriesEntryIdRouteWithChildren
  '/api/v1/ledger/chain-verification': typeof ApiV1LedgerChainVerificationRoute
  '/api/v1/members/$memberId': typeof ApiV1MembersMemberIdRoute
  '/api/v1/reports/balance-sheet': typeof ApiV1ReportsBalanceSheetRoute
  '/api/v1/reports/overdue-invoices': typeof ApiV1ReportsOverdueInvoicesRoute
  '/api/v1/reports/profit-and-loss': typeof ApiV1ReportsProfitAndLossRoute
  '/api/v1/reports/trial-balance': typeof ApiV1ReportsTrialBalanceRoute
  '/api/v1/rgs/coverage': typeof ApiV1RgsCoverageRoute
  '/api/v1/rgs/mappings': typeof ApiV1RgsMappingsRoute
  '/api/v1/rgs/upgrade-preview': typeof ApiV1RgsUpgradePreviewRoute
  '/api/v1/sales-invoices/$invoiceId': typeof ApiV1SalesInvoicesInvoiceIdRouteWithChildren
  '/api/v1/setup/charts': typeof ApiV1SetupChartsRoute
  '/api/v1/journal-entries/$entryId/reversal': typeof ApiV1JournalEntriesEntryIdReversalRoute
  '/api/v1/sales-invoices/$invoiceId/issue': typeof ApiV1SalesInvoicesInvoiceIdIssueRoute
}
export interface FileRoutesByTo {
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/accounts': typeof AppAccountsRoute
  '/members': typeof AppMembersRoute
  '/': typeof AppIndexRoute
  '/entries/$entryId': typeof AppEntriesEntryIdRoute
  '/entries/new': typeof AppEntriesNewRoute
  '/reports/balance-sheet': typeof AppReportsBalanceSheetRoute
  '/reports/profit-and-loss': typeof AppReportsProfitAndLossRoute
  '/reports/trial-balance': typeof AppReportsTrialBalanceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/accounts': typeof ApiV1AccountsRoute
  '/api/v1/contacts': typeof ApiV1ContactsRoute
  '/api/v1/fiscal-years': typeof ApiV1FiscalYearsRouteWithChildren
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/journal-entries': typeof ApiV1JournalEntriesRouteWithChildren
  '/api/v1/members': typeof ApiV1MembersRouteWithChildren
  '/api/v1/sales-invoices': typeof ApiV1SalesInvoicesRouteWithChildren
  '/api/v1/tax-codes': typeof ApiV1TaxCodesRoute
  '/entries': typeof AppEntriesIndexRoute
  '/api/v1/entities/$entityId': typeof ApiV1EntitiesEntityIdRoute
  '/api/v1/exports/audit-file': typeof ApiV1ExportsAuditFileRoute
  '/api/v1/fiscal-years/close': typeof ApiV1FiscalYearsCloseRoute
  '/api/v1/imports/audit-file': typeof ApiV1ImportsAuditFileRoute
  '/api/v1/journal-entries/$entryId': typeof ApiV1JournalEntriesEntryIdRouteWithChildren
  '/api/v1/ledger/chain-verification': typeof ApiV1LedgerChainVerificationRoute
  '/api/v1/members/$memberId': typeof ApiV1MembersMemberIdRoute
  '/api/v1/reports/balance-sheet': typeof ApiV1ReportsBalanceSheetRoute
  '/api/v1/reports/overdue-invoices': typeof ApiV1ReportsOverdueInvoicesRoute
  '/api/v1/reports/profit-and-loss': typeof ApiV1ReportsProfitAndLossRoute
  '/api/v1/reports/trial-balance': typeof ApiV1ReportsTrialBalanceRoute
  '/api/v1/rgs/coverage': typeof ApiV1RgsCoverageRoute
  '/api/v1/rgs/mappings': typeof ApiV1RgsMappingsRoute
  '/api/v1/rgs/upgrade-preview': typeof ApiV1RgsUpgradePreviewRoute
  '/api/v1/sales-invoices/$invoiceId': typeof ApiV1SalesInvoicesInvoiceIdRouteWithChildren
  '/api/v1/setup/charts': typeof ApiV1SetupChartsRoute
  '/api/v1/journal-entries/$entryId/reversal': typeof ApiV1JournalEntriesEntryIdReversalRoute
  '/api/v1/sales-invoices/$invoiceId/issue': typeof ApiV1SalesInvoicesInvoiceIdIssueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/entries/$entryId': typeof AppEntriesEntryIdRoute
  '/_app/entries/new': typeof AppEntriesNewRoute
  '/_app/reports/balance-sheet': typeof AppReportsBalanceSheetRoute
  '/_app/reports/profit-and-loss': typeof AppReportsProfitAndLossRoute
  '/_app/reports/trial-balance': typeof AppReportsTrialBalanceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/accounts': typeof ApiV1AccountsRoute
  '/api/v1/contacts': typeof ApiV1ContactsRoute
  '/api/v1/fiscal-years': typeof ApiV1FiscalYearsRouteWithChildren
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/journal-entries': typeof ApiV1JournalEntriesRouteWithChildren
  '/api/v1/members': typeof ApiV1MembersRouteWithChildren
  '/api/v1/sales-invoices': typeof ApiV1SalesInvoicesRouteWithChildren
  '/api/v1/tax-codes': typeof ApiV1TaxCodesRoute
  '/_app/entries/': typeof AppEntriesIndexRoute
  '/api/v1/entities/$entityId': typeof ApiV1EntitiesEntityIdRoute
  '/api/v1/exports/audit-file': typeof ApiV1ExportsAuditFileRoute
  '/api/v1/fiscal-years/close': typeof ApiV1FiscalYearsCloseRoute
  '/api/v1/imports/audit-file': typeof ApiV1ImportsAuditFileRoute
  '/api/v1/journal-entries/$entryId': typeof ApiV1JournalEntriesEntryIdRouteWithChildren
  '/api/v1/ledger/chain-verification': typeof ApiV1LedgerChainVerificationRoute
  '/api/v1/members/$memberId': typeof ApiV1MembersMemberIdRoute
  '/api/v1/reports/balance-sheet': typeof ApiV1ReportsBalanceSheetRoute
  '/api/v1/reports/overdue-invoices': typeof ApiV1ReportsOverdueInvoicesRoute
  '/api/v1/reports/profit-and-loss': typeof ApiV1ReportsProfitAndLossRoute
  '/api/v1/reports/trial-balance': typeof ApiV1ReportsTrialBalanceRoute
  '/api/v1/rgs/coverage': typeof ApiV1RgsCoverageRoute
  '/api/v1/rgs/mappings': typeof ApiV1RgsMappingsRoute
  '/api/v1/rgs/upgrade-preview': typeof ApiV1RgsUpgradePreviewRoute
  '/api/v1/sales-invoices/$invoiceId': typeof ApiV1SalesInvoicesInvoiceIdRouteWithChildren
  '/api/v1/setup/charts': typeof ApiV1SetupChartsRoute
  '/api/v1/journal-entries/$entryId/reversal': typeof ApiV1JournalEntriesEntryIdReversalRoute
  '/api/v1/sales-invoices/$invoiceId/issue': typeof ApiV1SalesInvoicesInvoiceIdIssueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/sign-in'
    | '/sign-out'
    | '/accounts'
    | '/members'
    | '/entries/$entryId'
    | '/entries/new'
    | '/reports/balance-sheet'
    | '/reports/profit-and-loss'
    | '/reports/trial-balance'
    | '/api/auth/$'
    | '/api/v1/accounts'
    | '/api/v1/contacts'
    | '/api/v1/fiscal-years'
    | '/api/v1/health'
    | '/api/v1/journal-entries'
    | '/api/v1/members'
    | '/api/v1/sales-invoices'
    | '/api/v1/tax-codes'
    | '/entries/'
    | '/api/v1/entities/$entityId'
    | '/api/v1/exports/audit-file'
    | '/api/v1/fiscal-years/close'
    | '/api/v1/imports/audit-file'
    | '/api/v1/journal-entries/$entryId'
    | '/api/v1/ledger/chain-verification'
    | '/api/v1/members/$memberId'
    | '/api/v1/reports/balance-sheet'
    | '/api/v1/reports/overdue-invoices'
    | '/api/v1/reports/profit-and-loss'
    | '/api/v1/reports/trial-balance'
    | '/api/v1/rgs/coverage'
    | '/api/v1/rgs/mappings'
    | '/api/v1/rgs/upgrade-preview'
    | '/api/v1/sales-invoices/$invoiceId'
    | '/api/v1/setup/charts'
    | '/api/v1/journal-entries/$entryId/reversal'
    | '/api/v1/sales-invoices/$invoiceId/issue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/sign-in'
    | '/sign-out'
    | '/accounts'
    | '/members'
    | '/'
    | '/entries/$entryId'
    | '/entries/new'
    | '/reports/balance-sheet'
    | '/reports/profit-and-loss'
    | '/reports/trial-balance'
    | '/api/auth/$'
    | '/api/v1/accounts'
    | '/api/v1/contacts'
    | '/api/v1/fiscal-years'
    | '/api/v1/health'
    | '/api/v1/journal-entries'
    | '/api/v1/members'
    | '/api/v1/sales-invoices'
    | '/api/v1/tax-codes'
    | '/entries'
    | '/api/v1/entities/$entityId'
    | '/api/v1/exports/audit-file'
    | '/api/v1/fiscal-years/close'
    | '/api/v1/imports/audit-file'
    | '/api/v1/journal-entries/$entryId'
    | '/api/v1/ledger/chain-verification'
    | '/api/v1/members/$memberId'
    | '/api/v1/reports/balance-sheet'
    | '/api/v1/reports/overdue-invoices'
    | '/api/v1/reports/profit-and-loss'
    | '/api/v1/reports/trial-balance'
    | '/api/v1/rgs/coverage'
    | '/api/v1/rgs/mappings'
    | '/api/v1/rgs/upgrade-preview'
    | '/api/v1/sales-invoices/$invoiceId'
    | '/api/v1/setup/charts'
    | '/api/v1/journal-entries/$entryId/reversal'
    | '/api/v1/sales-invoices/$invoiceId/issue'
  id:
    | '__root__'
    | '/_app'
    | '/setup'
    | '/sign-in'
    | '/sign-out'
    | '/_app/accounts'
    | '/_app/members'
    | '/_app/'
    | '/_app/entries/$entryId'
    | '/_app/entries/new'
    | '/_app/reports/balance-sheet'
    | '/_app/reports/profit-and-loss'
    | '/_app/reports/trial-balance'
    | '/api/auth/$'
    | '/api/v1/accounts'
    | '/api/v1/contacts'
    | '/api/v1/fiscal-years'
    | '/api/v1/health'
    | '/api/v1/journal-entries'
    | '/api/v1/members'
    | '/api/v1/sales-invoices'
    | '/api/v1/tax-codes'
    | '/_app/entries/'
    | '/api/v1/entities/$entityId'
    | '/api/v1/exports/audit-file'
    | '/api/v1/fiscal-years/close'
    | '/api/v1/imports/audit-file'
    | '/api/v1/journal-entries/$entryId'
    | '/api/v1/ledger/chain-verification'
    | '/api/v1/members/$memberId'
    | '/api/v1/reports/balance-sheet'
    | '/api/v1/reports/overdue-invoices'
    | '/api/v1/reports/profit-and-loss'
    | '/api/v1/reports/trial-balance'
    | '/api/v1/rgs/coverage'
    | '/api/v1/rgs/mappings'
    | '/api/v1/rgs/upgrade-preview'
    | '/api/v1/sales-invoices/$invoiceId'
    | '/api/v1/setup/charts'
    | '/api/v1/journal-entries/$entryId/reversal'
    | '/api/v1/sales-invoices/$invoiceId/issue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
  SignOutRoute: typeof SignOutRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1AccountsRoute: typeof ApiV1AccountsRoute
  ApiV1ContactsRoute: typeof ApiV1ContactsRoute
  ApiV1FiscalYearsRoute: typeof ApiV1FiscalYearsRouteWithChildren
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1JournalEntriesRoute: typeof ApiV1JournalEntriesRouteWithChildren
  ApiV1MembersRoute: typeof ApiV1MembersRouteWithChildren
  ApiV1SalesInvoicesRoute: typeof ApiV1SalesInvoicesRouteWithChildren
  ApiV1TaxCodesRoute: typeof ApiV1TaxCodesRoute
  ApiV1EntitiesEntityIdRoute: typeof ApiV1EntitiesEntityIdRoute
  ApiV1ExportsAuditFileRoute: typeof ApiV1ExportsAuditFileRoute
  ApiV1ImportsAuditFileRoute: typeof ApiV1ImportsAuditFileRoute
  ApiV1LedgerChainVerificationRoute: typeof ApiV1LedgerChainVerificationRoute
  ApiV1ReportsBalanceSheetRoute: typeof ApiV1ReportsBalanceSheetRoute
  ApiV1ReportsOverdueInvoicesRoute: typeof ApiV1ReportsOverdueInvoicesRoute
  ApiV1ReportsProfitAndLossRoute: typeof ApiV1ReportsProfitAndLossRoute
  ApiV1ReportsTrialBalanceRoute: typeof ApiV1ReportsTrialBalanceRoute
  ApiV1RgsCoverageRoute: typeof ApiV1RgsCoverageRoute
  ApiV1RgsMappingsRoute: typeof ApiV1RgsMappingsRoute
  ApiV1RgsUpgradePreviewRoute: typeof ApiV1RgsUpgradePreviewRoute
  ApiV1SetupChartsRoute: typeof ApiV1SetupChartsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entries/': {
      id: '/_app/entries/'
      path: '/entries'
      fullPath: '/entries/'
      preLoaderRoute: typeof AppEntriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entries/$entryId': {
      id: '/_app/entries/$entryId'
      path: '/entries/$entryId'
      fullPath: '/entries/$entryId'
      preLoaderRoute: typeof AppEntriesEntryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entries/new': {
      id: '/_app/entries/new'
      path: '/entries/new'
      fullPath: '/entries/new'
      preLoaderRoute: typeof AppEntriesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/balance-sheet': {
      id: '/_app/reports/balance-sheet'
      path: '/reports/balance-sheet'
      fullPath: '/reports/balance-sheet'
      preLoaderRoute: typeof AppReportsBalanceSheetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/profit-and-loss': {
      id: '/_app/reports/profit-and-loss'
      path: '/reports/profit-and-loss'
      fullPath: '/reports/profit-and-loss'
      preLoaderRoute: typeof AppReportsProfitAndLossRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/trial-balance': {
      id: '/_app/reports/trial-balance'
      path: '/reports/trial-balance'
      fullPath: '/reports/trial-balance'
      preLoaderRoute: typeof AppReportsTrialBalanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts': {
      id: '/api/v1/accounts'
      path: '/api/v1/accounts'
      fullPath: '/api/v1/accounts'
      preLoaderRoute: typeof ApiV1AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/contacts': {
      id: '/api/v1/contacts'
      path: '/api/v1/contacts'
      fullPath: '/api/v1/contacts'
      preLoaderRoute: typeof ApiV1ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/fiscal-years': {
      id: '/api/v1/fiscal-years'
      path: '/api/v1/fiscal-years'
      fullPath: '/api/v1/fiscal-years'
      preLoaderRoute: typeof ApiV1FiscalYearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/journal-entries': {
      id: '/api/v1/journal-entries'
      path: '/api/v1/journal-entries'
      fullPath: '/api/v1/journal-entries'
      preLoaderRoute: typeof ApiV1JournalEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/members': {
      id: '/api/v1/members'
      path: '/api/v1/members'
      fullPath: '/api/v1/members'
      preLoaderRoute: typeof ApiV1MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sales-invoices': {
      id: '/api/v1/sales-invoices'
      path: '/api/v1/sales-invoices'
      fullPath: '/api/v1/sales-invoices'
      preLoaderRoute: typeof ApiV1SalesInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tax-codes': {
      id: '/api/v1/tax-codes'
      path: '/api/v1/tax-codes'
      fullPath: '/api/v1/tax-codes'
      preLoaderRoute: typeof ApiV1TaxCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/entities/$entityId': {
      id: '/api/v1/entities/$entityId'
      path: '/api/v1/entities/$entityId'
      fullPath: '/api/v1/entities/$entityId'
      preLoaderRoute: typeof ApiV1EntitiesEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/exports/audit-file': {
      id: '/api/v1/exports/audit-file'
      path: '/api/v1/exports/audit-file'
      fullPath: '/api/v1/exports/audit-file'
      preLoaderRoute: typeof ApiV1ExportsAuditFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/fiscal-years/close': {
      id: '/api/v1/fiscal-years/close'
      path: '/close'
      fullPath: '/api/v1/fiscal-years/close'
      preLoaderRoute: typeof ApiV1FiscalYearsCloseRouteImport
      parentRoute: typeof ApiV1FiscalYearsRoute
    }
    '/api/v1/imports/audit-file': {
      id: '/api/v1/imports/audit-file'
      path: '/api/v1/imports/audit-file'
      fullPath: '/api/v1/imports/audit-file'
      preLoaderRoute: typeof ApiV1ImportsAuditFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/journal-entries/$entryId': {
      id: '/api/v1/journal-entries/$entryId'
      path: '/$entryId'
      fullPath: '/api/v1/journal-entries/$entryId'
      preLoaderRoute: typeof ApiV1JournalEntriesEntryIdRouteImport
      parentRoute: typeof ApiV1JournalEntriesRoute
    }
    '/api/v1/ledger/chain-verification': {
      id: '/api/v1/ledger/chain-verification'
      path: '/api/v1/ledger/chain-verification'
      fullPath: '/api/v1/ledger/chain-verification'
      preLoaderRoute: typeof ApiV1LedgerChainVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/members/$memberId': {
      id: '/api/v1/members/$memberId'
      path: '/$memberId'
      fullPath: '/api/v1/members/$memberId'
      preLoaderRoute: typeof ApiV1MembersMemberIdRouteImport
      parentRoute: typeof ApiV1MembersRoute
    }
    '/api/v1/reports/balance-sheet': {
      id: '/api/v1/reports/balance-sheet'
      path: '/api/v1/reports/balance-sheet'
      fullPath: '/api/v1/reports/balance-sheet'
      preLoaderRoute: typeof ApiV1ReportsBalanceSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports/overdue-invoices': {
      id: '/api/v1/reports/overdue-invoices'
      path: '/api/v1/reports/overdue-invoices'
      fullPath: '/api/v1/reports/overdue-invoices'
      preLoaderRoute: typeof ApiV1ReportsOverdueInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports/profit-and-loss': {
      id: '/api/v1/reports/profit-and-loss'
      path: '/api/v1/reports/profit-and-loss'
      fullPath: '/api/v1/reports/profit-and-loss'
      preLoaderRoute: typeof ApiV1ReportsProfitAndLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports/trial-balance': {
      id: '/api/v1/reports/trial-balance'
      path: '/api/v1/reports/trial-balance'
      fullPath: '/api/v1/reports/trial-balance'
      preLoaderRoute: typeof ApiV1ReportsTrialBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/rgs/coverage': {
      id: '/api/v1/rgs/coverage'
      path: '/api/v1/rgs/coverage'
      fullPath: '/api/v1/rgs/coverage'
      preLoaderRoute: typeof ApiV1RgsCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/rgs/mappings': {
      id: '/api/v1/rgs/mappings'
      path: '/api/v1/rgs/mappings'
      fullPath: '/api/v1/rgs/mappings'
      preLoaderRoute: typeof ApiV1RgsMappingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/rgs/upgrade-preview': {
      id: '/api/v1/rgs/upgrade-preview'
      path: '/api/v1/rgs/upgrade-preview'
      fullPath: '/api/v1/rgs/upgrade-preview'
      preLoaderRoute: typeof ApiV1RgsUpgradePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sales-invoices/$invoiceId': {
      id: '/api/v1/sales-invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/api/v1/sales-invoices/$invoiceId'
      preLoaderRoute: typeof ApiV1SalesInvoicesInvoiceIdRouteImport
      parentRoute: typeof ApiV1SalesInvoicesRoute
    }
    '/api/v1/setup/charts': {
      id: '/api/v1/setup/charts'
      path: '/api/v1/setup/charts'
      fullPath: '/api/v1/setup/charts'
      preLoaderRoute: typeof ApiV1SetupChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/journal-entries/$entryId/reversal': {
      id: '/api/v1/journal-entries/$entryId/reversal'
      path: '/reversal'
      fullPath: '/api/v1/journal-entries/$entryId/reversal'
      preLoaderRoute: typeof ApiV1JournalEntriesEntryIdReversalRouteImport
      parentRoute: typeof ApiV1JournalEntriesEntryIdRoute
    }
    '/api/v1/sales-invoices/$invoiceId/issue': {
      id: '/api/v1/sales-invoices/$invoiceId/issue'
      path: '/issue'
      fullPath: '/api/v1/sales-invoices/$invoiceId/issue'
      preLoaderRoute: typeof ApiV1SalesInvoicesInvoiceIdIssueRouteImport
      parentRoute: typeof ApiV1SalesInvoicesInvoiceIdRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppMembersRoute: typeof AppMembersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEntriesEntryIdRoute: typeof AppEntriesEntryIdRoute
  AppEntriesNewRoute: typeof AppEntriesNewRoute
  AppReportsBalanceSheetRoute: typeof AppReportsBalanceSheetRoute
  AppReportsProfitAndLossRoute: typeof AppReportsProfitAndLossRoute
  AppReportsTrialBalanceRoute: typeof AppReportsTrialBalanceRoute
  AppEntriesIndexRoute: typeof AppEntriesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppMembersRoute: AppMembersRoute,
  AppIndexRoute: AppIndexRoute,
  AppEntriesEntryIdRoute: AppEntriesEntryIdRoute,
  AppEntriesNewRoute: AppEntriesNewRoute,
  AppReportsBalanceSheetRoute: AppReportsBalanceSheetRoute,
  AppReportsProfitAndLossRoute: AppReportsProfitAndLossRoute,
  AppReportsTrialBalanceRoute: AppReportsTrialBalanceRoute,
  AppEntriesIndexRoute: AppEntriesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiV1FiscalYearsRouteChildren {
  ApiV1FiscalYearsCloseRoute: typeof ApiV1FiscalYearsCloseRoute
}

const ApiV1FiscalYearsRouteChildren: ApiV1FiscalYearsRouteChildren = {
  ApiV1FiscalYearsCloseRoute: ApiV1FiscalYearsCloseRoute,
}

const ApiV1FiscalYearsRouteWithChildren =
  ApiV1FiscalYearsRoute._addFileChildren(ApiV1FiscalYearsRouteChildren)

interface ApiV1JournalEntriesEntryIdRouteChildren {
  ApiV1JournalEntriesEntryIdReversalRoute: typeof ApiV1JournalEntriesEntryIdReversalRoute
}

const ApiV1JournalEntriesEntryIdRouteChildren: ApiV1JournalEntriesEntryIdRouteChildren =
  {
    ApiV1JournalEntriesEntryIdReversalRoute:
      ApiV1JournalEntriesEntryIdReversalRoute,
  }

const ApiV1JournalEntriesEntryIdRouteWithChildren =
  ApiV1JournalEntriesEntryIdRoute._addFileChildren(
    ApiV1JournalEntriesEntryIdRouteChildren,
  )

interface ApiV1JournalEntriesRouteChildren {
  ApiV1JournalEntriesEntryIdRoute: typeof ApiV1JournalEntriesEntryIdRouteWithChildren
}

const ApiV1JournalEntriesRouteChildren: ApiV1JournalEntriesRouteChildren = {
  ApiV1JournalEntriesEntryIdRoute: ApiV1JournalEntriesEntryIdRouteWithChildren,
}

const ApiV1JournalEntriesRouteWithChildren =
  ApiV1JournalEntriesRoute._addFileChildren(ApiV1JournalEntriesRouteChildren)

interface ApiV1MembersRouteChildren {
  ApiV1MembersMemberIdRoute: typeof ApiV1MembersMemberIdRoute
}

const ApiV1MembersRouteChildren: ApiV1MembersRouteChildren = {
  ApiV1MembersMemberIdRoute: ApiV1MembersMemberIdRoute,
}

const ApiV1MembersRouteWithChildren = ApiV1MembersRoute._addFileChildren(
  ApiV1MembersRouteChildren,
)

interface ApiV1SalesInvoicesInvoiceIdRouteChildren {
  ApiV1SalesInvoicesInvoiceIdIssueRoute: typeof ApiV1SalesInvoicesInvoiceIdIssueRoute
}

const ApiV1SalesInvoicesInvoiceIdRouteChildren: ApiV1SalesInvoicesInvoiceIdRouteChildren =
  {
    ApiV1SalesInvoicesInvoiceIdIssueRoute:
      ApiV1SalesInvoicesInvoiceIdIssueRoute,
  }

const ApiV1SalesInvoicesInvoiceIdRouteWithChildren =
  ApiV1SalesInvoicesInvoiceIdRoute._addFileChildren(
    ApiV1SalesInvoicesInvoiceIdRouteChildren,
  )

interface ApiV1SalesInvoicesRouteChildren {
  ApiV1SalesInvoicesInvoiceIdRoute: typeof ApiV1SalesInvoicesInvoiceIdRouteWithChildren
}

const ApiV1SalesInvoicesRouteChildren: ApiV1SalesInvoicesRouteChildren = {
  ApiV1SalesInvoicesInvoiceIdRoute:
    ApiV1SalesInvoicesInvoiceIdRouteWithChildren,
}

const ApiV1SalesInvoicesRouteWithChildren =
  ApiV1SalesInvoicesRoute._addFileChildren(ApiV1SalesInvoicesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
  SignOutRoute: SignOutRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1AccountsRoute: ApiV1AccountsRoute,
  ApiV1ContactsRoute: ApiV1ContactsRoute,
  ApiV1FiscalYearsRoute: ApiV1FiscalYearsRouteWithChildren,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1JournalEntriesRoute: ApiV1JournalEntriesRouteWithChildren,
  ApiV1MembersRoute: ApiV1MembersRouteWithChildren,
  ApiV1SalesInvoicesRoute: ApiV1SalesInvoicesRouteWithChildren,
  ApiV1TaxCodesRoute: ApiV1TaxCodesRoute,
  ApiV1EntitiesEntityIdRoute: ApiV1EntitiesEntityIdRoute,
  ApiV1ExportsAuditFileRoute: ApiV1ExportsAuditFileRoute,
  ApiV1ImportsAuditFileRoute: ApiV1ImportsAuditFileRoute,
  ApiV1LedgerChainVerificationRoute: ApiV1LedgerChainVerificationRoute,
  ApiV1ReportsBalanceSheetRoute: ApiV1ReportsBalanceSheetRoute,
  ApiV1ReportsOverdueInvoicesRoute: ApiV1ReportsOverdueInvoicesRoute,
  ApiV1ReportsProfitAndLossRoute: ApiV1ReportsProfitAndLossRoute,
  ApiV1ReportsTrialBalanceRoute: ApiV1ReportsTrialBalanceRoute,
  ApiV1RgsCoverageRoute: ApiV1RgsCoverageRoute,
  ApiV1RgsMappingsRoute: ApiV1RgsMappingsRoute,
  ApiV1RgsUpgradePreviewRoute: ApiV1RgsUpgradePreviewRoute,
  ApiV1SetupChartsRoute: ApiV1SetupChartsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
