/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'
import { Route as AppContactsRouteImport } from './routes/_app/contacts'
import { Route as AppDunningRouteImport } from './routes/_app/dunning'
import { Route as AppMembersRouteImport } from './routes/_app/members'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppBankIndexRouteImport } from './routes/_app/bank.index'
import { Route as AppBankMatchRouteImport } from './routes/_app/bank.match'
import { Route as AppEntriesIndexRouteImport } from './routes/_app/entries.index'
import { Route as AppEntriesEntryIdRouteImport } from './routes/_app/entries.$entryId'
import { Route as AppEntriesNewRouteImport } from './routes/_app/entries.new'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices.index'
import { Route as AppInvoicesInvoiceIdRouteImport } from './routes/_app/invoices.$invoiceId'
import { Route as AppInvoicesNewRouteImport } from './routes/_app/invoices.new'
import { Route as AppPaymentsIndexRouteImport } from './routes/_app/payments.index'
import { Route as AppPaymentsBatchIdRouteImport } from './routes/_app/payments.$batchId'
import { Route as AppReportsBalanceSheetRouteImport } from './routes/_app/reports.balance-sheet'
import { Route as AppReportsProfitAndLossRouteImport } from './routes/_app/reports.profit-and-loss'
import { Route as AppReportsTrialBalanceRouteImport } from './routes/_app/reports.trial-balance'
import { Route as AppVatIndexRouteImport } from './routes/_app/vat.index'
import { Route as AppVatPeriodRouteImport } from './routes/_app/vat.$period'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiV1AccountsRouteImport } from './routes/api/v1/accounts'
import { Route as ApiV1BankAccountsRouteImport } from './routes/api/v1/bank-accounts'
import { Route as ApiV1BankMatchRulesRouteImport } from './routes/api/v1/bank-match-rules'
import { Route as ApiV1BankStatementsRouteImport } from './routes/api/v1/bank-statements'
import { Route as ApiV1BankTransactionsRouteImport } from './routes/api/v1/bank-transactions'
import { Route as ApiV1ContactsRouteImport } from './routes/api/v1/contacts'
import { Route as ApiV1EntityRouteImport } from './routes/api/v1/entity'
import { Route as ApiV1FiscalYearsRouteImport } from './routes/api/v1/fiscal-years'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1JournalEntriesRouteImport } from './routes/api/v1/journal-entries'
import { Route as ApiV1MembersRouteImport } from './routes/api/v1/members'
import { Route as ApiV1PaymentBatchesRouteImport } from './routes/api/v1/payment-batches'
import { Route as ApiV1SalesInvoicesRouteImport } from './routes/api/v1/sales-invoices'
import { Route as ApiV1TaxCodesRouteImport } from './routes/api/v1/tax-codes'
import { Route as AppVatIcpPeriodRouteImport } from './routes/_app/vat.icp.$period'
import { Route as ApiV1BankMatchRulesRuleIdRouteImport } from './routes/api/v1/bank-match-rules.$ruleId'
import { Route as ApiV1EntitiesEntityIdRouteImport } from './routes/api/v1/entities.$entityId'
import { Route as ApiV1ExportsAuditFileRouteImport } from './routes/api/v1/exports.audit-file'
import { Route as ApiV1FiscalYearsCloseRouteImport } from './routes/api/v1/fiscal-years.close'
import { Route as ApiV1ImportsAuditFileRouteImport } from './routes/api/v1/imports.audit-file'
import { Route as ApiV1JournalEntriesEntryIdRouteImport } from './routes/api/v1/journal-entries.$entryId'
import { Route as ApiV1LedgerChainVerificationRouteImport } from './routes/api/v1/ledger.chain-verification'
import { Route as ApiV1MembersMemberIdRouteImport } from './routes/api/v1/members.$memberId'
import { Route as ApiV1PaymentBatchesBatchIdRouteImport } from './routes/api/v1/payment-batches.$batchId'
import { Route as ApiV1ReportsBalanceSheetRouteImport } from './routes/api/v1/reports.balance-sheet'
import { Route as ApiV1ReportsDunningRouteImport } from './routes/api/v1/reports.dunning'
import { Route as ApiV1ReportsOverdueInvoicesRouteImport } from './routes/api/v1/reports.overdue-invoices'
import { Route as ApiV1ReportsProfitAndLossRouteImport } from './routes/api/v1/reports.profit-and-loss'
import { Route as ApiV1ReportsTrialBalanceRouteImport } from './routes/api/v1/reports.trial-balance'
import { Route as ApiV1RgsCoverageRouteImport } from './routes/api/v1/rgs.coverage'
import { Route as ApiV1RgsMappingsRouteImport } from './routes/api/v1/rgs.mappings'
import { Route as ApiV1RgsUpgradePreviewRouteImport } from './routes/api/v1/rgs.upgrade-preview'
import { Route as ApiV1SalesInvoicesInvoiceIdRouteImport } from './routes/api/v1/sales-invoices.$invoiceId'
import { Route as ApiV1SetupChartsRouteImport } from './routes/api/v1/setup.charts'
import { Route as ApiV1VatFilingsRouteImport } from './routes/api/v1/vat.filings'
import { Route as ApiV1VatNumberChecksRouteImport } from './routes/api/v1/vat.number-checks'
import { Route as ApiV1VatPeriodsRouteImport } from './routes/api/v1/vat.periods'
import { Route as ApiV1BankTransactionsTransactionIdIgnoreRouteImport } from './routes/api/v1/bank-transactions.$transactionId.ignore'
import { Route as ApiV1BankTransactionsTransactionIdMatchRouteImport } from './routes/api/v1/bank-transactions.$transactionId.match'
import { Route as ApiV1BankTransactionsTransactionIdSuggestionsRouteImport } from './routes/api/v1/bank-transactions.$transactionId.suggestions'
import { Route as ApiV1JournalEntriesEntryIdReversalRouteImport } from './routes/api/v1/journal-entries.$entryId.reversal'
import { Route as ApiV1PaymentBatchesBatchIdInstructionsRouteImport } from './routes/api/v1/payment-batches.$batchId.instructions'
import { Route as ApiV1PaymentBatchesBatchIdPain001RouteImport } from './routes/api/v1/payment-batches.$batchId.pain001'
import { Route as ApiV1PaymentBatchesBatchIdTransitionsRouteImport } from './routes/api/v1/payment-batches.$batchId.transitions'
import { Route as ApiV1SalesInvoicesInvoiceIdDeliveriesRouteImport } from './routes/api/v1/sales-invoices.$invoiceId.deliveries'
import { Route as ApiV1SalesInvoicesInvoiceIdIssueRouteImport } from './routes/api/v1/sales-invoices.$invoiceId.issue'
import { Route as ApiV1SalesInvoicesInvoiceIdPdfRouteImport } from './routes/api/v1/sales-invoices.$invoiceId.pdf'
import { Route as ApiV1SalesInvoicesInvoiceIdRemindersRouteImport } from './routes/api/v1/sales-invoices.$invoiceId.reminders'
import { Route as ApiV1SalesInvoicesInvoiceIdSendRouteImport } from './routes/api/v1/sales-invoices.$invoiceId.send'
import { Route as ApiV1SalesInvoicesInvoiceIdUblRouteImport } from './routes/api/v1/sales-invoices.$invoiceId.ubl'
import { Route as ApiV1VatIcpPeriodRouteImport } from './routes/api/v1/vat.icp.$period'
import { Route as ApiV1VatReturnsPeriodRouteImport } from './routes/api/v1/vat.returns.$period'
import { Route as ApiV1PaymentBatchesBatchIdInstructionsInstructionIdRouteImport } from './routes/api/v1/payment-batches.$batchId.instructions.$instructionId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppDunningRoute = AppDunningRouteImport.update({
  id: '/dunning',
  path: '/dunning',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppBankIndexRoute = AppBankIndexRouteImport.update({
  id: '/bank/',
  path: '/bank/',
  getParentRoute: () => AppRoute,
} as any)
const AppBankMatchRoute = AppBankMatchRouteImport.update({
  id: '/bank/match',
  path: '/bank/match',
  getParentRoute: () => AppRoute,
} as any)
const AppEntriesIndexRoute = AppEntriesIndexRouteImport.update({
  id: '/entries/',
  path: '/entries/',
  getParentRoute: () => AppRoute,
} as any)
const AppEntriesEntryIdRoute = AppEntriesEntryIdRouteImport.update({
  id: '/entries/$entryId',
  path: '/entries/$entryId',
  getParentRoute: () => AppRoute,
} as any)
const AppEntriesNewRoute = AppEntriesNewRouteImport.update({
  id: '/entries/new',
  path: '/entries/new',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesInvoiceIdRoute = AppInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsIndexRoute = AppPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsBatchIdRoute = AppPaymentsBatchIdRouteImport.update({
  id: '/payments/$batchId',
  path: '/payments/$batchId',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsBalanceSheetRoute = AppReportsBalanceSheetRouteImport.update({
  id: '/reports/balance-sheet',
  path: '/reports/balance-sheet',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsProfitAndLossRoute = AppReportsProfitAndLossRouteImport.update({
  id: '/reports/profit-and-loss',
  path: '/reports/profit-and-loss',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsTrialBalanceRoute = AppReportsTrialBalanceRouteImport.update({
  id: '/reports/trial-balance',
  path: '/reports/trial-balance',
  getParentRoute: () => AppRoute,
} as any)
const AppVatIndexRoute = AppVatIndexRouteImport.update({
  id: '/vat/',
  path: '/vat/',
  getParentRoute: () => AppRoute,
} as any)
const AppVatPeriodRoute = AppVatPeriodRouteImport.update({
  id: '/vat/$period',
  path: '/vat/$period',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AccountsRoute = ApiV1AccountsRouteImport.update({
  id: '/api/v1/accounts',
  path: '/api/v1/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BankAccountsRoute = ApiV1BankAccountsRouteImport.update({
  id: '/api/v1/bank-accounts',
  path: '/api/v1/bank-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BankMatchRulesRoute = ApiV1BankMatchRulesRouteImport.update({
  id: '/api/v1/bank-match-rules',
  path: '/api/v1/bank-match-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BankStatementsRoute = ApiV1BankStatementsRouteImport.update({
  id: '/api/v1/bank-statements',
  path: '/api/v1/bank-statements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BankTransactionsRoute = ApiV1BankTransactionsRouteImport.update({
  id: '/api/v1/bank-transactions',
  path: '/api/v1/bank-transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ContactsRoute = ApiV1ContactsRouteImport.update({
  id: '/api/v1/contacts',
  path: '/api/v1/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EntityRoute = ApiV1EntityRouteImport.update({
  id: '/api/v1/entity',
  path: '/api/v1/entity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FiscalYearsRoute = ApiV1FiscalYearsRouteImport.update({
  id: '/api/v1/fiscal-years',
  path: '/api/v1/fiscal-years',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JournalEntriesRoute = ApiV1JournalEntriesRouteImport.update({
  id: '/api/v1/journal-entries',
  path: '/api/v1/journal-entries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MembersRoute = ApiV1MembersRouteImport.update({
  id: '/api/v1/members',
  path: '/api/v1/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PaymentBatchesRoute = ApiV1PaymentBatchesRouteImport.update({
  id: '/api/v1/payment-batches',
  path: '/api/v1/payment-batches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SalesInvoicesRoute = ApiV1SalesInvoicesRouteImport.update({
  id: '/api/v1/sales-invoices',
  path: '/api/v1/sales-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TaxCodesRoute = ApiV1TaxCodesRouteImport.update({
  id: '/api/v1/tax-codes',
  path: '/api/v1/tax-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVatIcpPeriodRoute = AppVatIcpPeriodRouteImport.update({
  id: '/vat/icp/$period',
  path: '/vat/icp/$period',
  getParentRoute: () => AppRoute,
} as any)
const ApiV1BankMatchRulesRuleIdRoute =
  ApiV1BankMatchRulesRuleIdRouteImport.update({
    id: '/$ruleId',
    path: '/$ruleId',
    getParentRoute: () => ApiV1BankMatchRulesRoute,
  } as any)
const ApiV1EntitiesEntityIdRoute = ApiV1EntitiesEntityIdRouteImport.update({
  id: '/api/v1/entities/$entityId',
  path: '/api/v1/entities/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExportsAuditFileRoute = ApiV1ExportsAuditFileRouteImport.update({
  id: '/api/v1/exports/audit-file',
  path: '/api/v1/exports/audit-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FiscalYearsCloseRoute = ApiV1FiscalYearsCloseRouteImport.update({
  id: '/close',
  path: '/close',
  getParentRoute: () => ApiV1FiscalYearsRoute,
} as any)
const ApiV1ImportsAuditFileRoute = ApiV1ImportsAuditFileRouteImport.update({
  id: '/api/v1/imports/audit-file',
  path: '/api/v1/imports/audit-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JournalEntriesEntryIdRoute =
  ApiV1JournalEntriesEntryIdRouteImport.update({
    id: '/$entryId',
    path: '/$entryId',
    getParentRoute: () => ApiV1JournalEntriesRoute,
  } as any)
const ApiV1LedgerChainVerificationRoute =
  ApiV1LedgerChainVerificationRouteImport.update({
    id: '/api/v1/ledger/chain-verification',
    path: '/api/v1/ledger/chain-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1MembersMemberIdRoute = ApiV1MembersMemberIdRouteImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => ApiV1MembersRoute,
} as any)
const ApiV1PaymentBatchesBatchIdRoute =
  ApiV1PaymentBatchesBatchIdRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => ApiV1PaymentBatchesRoute,
  } as any)
const ApiV1ReportsBalanceSheetRoute =
  ApiV1ReportsBalanceSheetRouteImport.update({
    id: '/api/v1/reports/balance-sheet',
    path: '/api/v1/reports/balance-sheet',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ReportsDunningRoute = ApiV1ReportsDunningRouteImport.update({
  id: '/api/v1/reports/dunning',
  path: '/api/v1/reports/dunning',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReportsOverdueInvoicesRoute =
  ApiV1ReportsOverdueInvoicesRouteImport.update({
    id: '/api/v1/reports/overdue-invoices',
    path: '/api/v1/reports/overdue-invoices',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ReportsProfitAndLossRoute =
  ApiV1ReportsProfitAndLossRouteImport.update({
    id: '/api/v1/reports/profit-and-loss',
    path: '/api/v1/reports/profit-and-loss',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ReportsTrialBalanceRoute =
  ApiV1ReportsTrialBalanceRouteImport.update({
    id: '/api/v1/reports/trial-balance',
    path: '/api/v1/reports/trial-balance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1RgsCoverageRoute = ApiV1RgsCoverageRouteImport.update({
  id: '/api/v1/rgs/coverage',
  path: '/api/v1/rgs/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RgsMappingsRoute = ApiV1RgsMappingsRouteImport.update({
  id: '/api/v1/rgs/mappings',
  path: '/api/v1/rgs/mappings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RgsUpgradePreviewRoute = ApiV1RgsUpgradePreviewRouteImport.update({
  id: '/api/v1/rgs/upgrade-preview',
  path: '/api/v1/rgs/upgrade-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SalesInvoicesInvoiceIdRoute =
  ApiV1SalesInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => ApiV1SalesInvoicesRoute,
  } as any)
const ApiV1SetupChartsRoute = ApiV1SetupChartsRouteImport.update({
  id: '/api/v1/setup/charts',
  path: '/api/v1/setup/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1VatFilingsRoute = ApiV1VatFilingsRouteImport.update({
  id: '/api/v1/vat/filings',
  path: '/api/v1/vat/filings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1VatNumberChecksRoute = ApiV1VatNumberChecksRouteImport.update({
  id: '/api/v1/vat/number-checks',
  path: '/api/v1/vat/number-checks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1VatPeriodsRoute = ApiV1VatPeriodsRouteImport.update({
  id: '/api/v1/vat/periods',
  path: '/api/v1/vat/periods',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BankTransactionsTransactionIdIgnoreRoute =
  ApiV1BankTransactionsTransactionIdIgnoreRouteImport.update({
    id: '/$transactionId/ignore',
    path: '/$transactionId/ignore',
    getParentRoute: () => ApiV1BankTransactionsRoute,
  } as any)
const ApiV1BankTransactionsTransactionIdMatchRoute =
  ApiV1BankTransactionsTransactionIdMatchRouteImport.update({
    id: '/$transactionId/match',
    path: '/$transactionId/match',
    getParentRoute: () => ApiV1BankTransactionsRoute,
  } as any)
const ApiV1BankTransactionsTransactionIdSuggestionsRoute =
  ApiV1BankTransactionsTransactionIdSuggestionsRouteImport.update({
    id: '/$transactionId/suggestions',
    path: '/$transactionId/suggestions',
    getParentRoute: () => ApiV1BankTransactionsRoute,
  } as any)
const ApiV1JournalEntriesEntryIdReversalRoute =
  ApiV1JournalEntriesEntryIdReversalRouteImport.update({
    id: '/reversal',
    path: '/reversal',
    getParentRoute: () => ApiV1JournalEntriesEntryIdRoute,
  } as any)
const ApiV1PaymentBatchesBatchIdInstructionsRoute =
  ApiV1PaymentBatchesBatchIdInstructionsRouteImport.update({
    id: '/instructions',
    path: '/instructions',
    getParentRoute: () => ApiV1PaymentBatchesBatchIdRoute,
  } as any)
const ApiV1PaymentBatchesBatchIdPain001Route =
  ApiV1PaymentBatchesBatchIdPain001RouteImport.update({
    id: '/pain001',
    path: '/pain001',
    getParentRoute: () => ApiV1PaymentBatchesBatchIdRoute,
  } as any)
const ApiV1PaymentBatchesBatchIdTransitionsRoute =
  ApiV1PaymentBatchesBatchIdTransitionsRouteImport.update({
    id: '/transitions',
    path: '/transitions',
    getParentRoute: () => ApiV1PaymentBatchesBatchIdRoute,
  } as any)
const ApiV1SalesInvoicesInvoiceIdDeliveriesRoute =
  ApiV1SalesInvoicesInvoiceIdDeliveriesRouteImport.update({
    id: '/deliveries',
    path: '/deliveries',
    getParentRoute: () => ApiV1SalesInvoicesInvoiceIdRoute,
  } as any)
const ApiV1SalesInvoicesInvoiceIdIssueRoute =
  ApiV1SalesInvoicesInvoiceIdIssueRouteImport.update({
    id: '/issue',
    path: '/issue',
    getParentRoute: () => ApiV1SalesInvoicesInvoiceIdRoute,
  } as any)
const ApiV1SalesInvoicesInvoiceIdPdfRoute =
  ApiV1SalesInvoicesInvoiceIdPdfRouteImport.update({
    id: '/pdf',
    path: '/pdf',
    getParentRoute: () => ApiV1SalesInvoicesInvoiceIdRoute,
  } as any)
const ApiV1SalesInvoicesInvoiceIdRemindersRoute =
  ApiV1SalesInvoicesInvoiceIdRemindersRouteImport.update({
    id: '/reminders',
    path: '/reminders',
    getParentRoute: () => ApiV1SalesInvoicesInvoiceIdRoute,
  } as any)
const ApiV1SalesInvoicesInvoiceIdSendRoute =
  ApiV1SalesInvoicesInvoiceIdSendRouteImport.update({
    id: '/send',
    path: '/send',
    getParentRoute: () => ApiV1SalesInvoicesInvoiceIdRoute,
  } as any)
const ApiV1SalesInvoicesInvoiceIdUblRoute =
  ApiV1SalesInvoicesInvoiceIdUblRouteImport.update({
    id: '/ubl',
    path: '/ubl',
    getParentRoute: () => ApiV1SalesInvoicesInvoiceIdRoute,
  } as any)
const ApiV1VatIcpPeriodRoute = ApiV1VatIcpPeriodRouteImport.update({
  id: '/api/v1/vat/icp/$period',
  path: '/api/v1/vat/icp/$period',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1VatReturnsPeriodRoute = ApiV1VatReturnsPeriodRouteImport.update({
  id: '/api/v1/vat/returns/$period',
  path: '/api/v1/vat/returns/$period',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1PaymentBatchesBatchIdInstructionsInstructionIdRoute =
  ApiV1PaymentBatchesBatchIdInstructionsInstructionIdRouteImport.update({
    id: '/$instructionId',
    path: '/$instructionId',
    getParentRoute: () => ApiV1PaymentBatchesBatchIdInstructionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/accounts': typeof AppAccountsRoute
  '/contacts': typeof AppContactsRoute
  '/dunning': typeof AppDunningRoute
  '/members': typeof AppMembersRoute
  '/settings': typeof AppSettingsRoute
  '/bank/match': typeof AppBankMatchRoute
  '/entries/$entryId': typeof AppEntriesEntryIdRoute
  '/entries/new': typeof AppEntriesNewRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/payments/$batchId': typeof AppPaymentsBatchIdRoute
  '/reports/balance-sheet': typeof AppReportsBalanceSheetRoute
  '/reports/profit-and-loss': typeof AppReportsProfitAndLossRoute
  '/reports/trial-balance': typeof AppReportsTrialBalanceRoute
  '/vat/$period': typeof AppVatPeriodRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/accounts': typeof ApiV1AccountsRoute
  '/api/v1/bank-accounts': typeof ApiV1BankAccountsRoute
  '/api/v1/bank-match-rules': typeof ApiV1BankMatchRulesRouteWithChildren
  '/api/v1/bank-statements': typeof ApiV1BankStatementsRoute
  '/api/v1/bank-transactions': typeof ApiV1BankTransactionsRouteWithChildren
  '/api/v1/contacts': typeof ApiV1ContactsRoute
  '/api/v1/entity': typeof ApiV1EntityRoute
  '/api/v1/fiscal-years': typeof ApiV1FiscalYearsRouteWithChildren
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/journal-entries': typeof ApiV1JournalEntriesRouteWithChildren
  '/api/v1/members': typeof ApiV1MembersRouteWithChildren
  '/api/v1/payment-batches': typeof ApiV1PaymentBatchesRouteWithChildren
  '/api/v1/sales-invoices': typeof ApiV1SalesInvoicesRouteWithChildren
  '/api/v1/tax-codes': typeof ApiV1TaxCodesRoute
  '/bank/': typeof AppBankIndexRoute
  '/entries/': typeof AppEntriesIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/payments/': typeof AppPaymentsIndexRoute
  '/vat/': typeof AppVatIndexRoute
  '/vat/icp/$period': typeof AppVatIcpPeriodRoute
  '/api/v1/bank-match-rules/$ruleId': typeof ApiV1BankMatchRulesRuleIdRoute
  '/api/v1/entities/$entityId': typeof ApiV1EntitiesEntityIdRoute
  '/api/v1/exports/audit-file': typeof ApiV1ExportsAuditFileRoute
  '/api/v1/fiscal-years/close': typeof ApiV1FiscalYearsCloseRoute
  '/api/v1/imports/audit-file': typeof ApiV1ImportsAuditFileRoute
  '/api/v1/journal-entries/$entryId': typeof ApiV1JournalEntriesEntryIdRouteWithChildren
  '/api/v1/ledger/chain-verification': typeof ApiV1LedgerChainVerificationRoute
  '/api/v1/members/$memberId': typeof ApiV1MembersMemberIdRoute
  '/api/v1/payment-batches/$batchId': typeof ApiV1PaymentBatchesBatchIdRouteWithChildren
  '/api/v1/reports/balance-sheet': typeof ApiV1ReportsBalanceSheetRoute
  '/api/v1/reports/dunning': typeof ApiV1ReportsDunningRoute
  '/api/v1/reports/overdue-invoices': typeof ApiV1ReportsOverdueInvoicesRoute
  '/api/v1/reports/profit-and-loss': typeof ApiV1ReportsProfitAndLossRoute
  '/api/v1/reports/trial-balance': typeof ApiV1ReportsTrialBalanceRoute
  '/api/v1/rgs/coverage': typeof ApiV1RgsCoverageRoute
  '/api/v1/rgs/mappings': typeof ApiV1RgsMappingsRoute
  '/api/v1/rgs/upgrade-preview': typeof ApiV1RgsUpgradePreviewRoute
  '/api/v1/sales-invoices/$invoiceId': typeof ApiV1SalesInvoicesInvoiceIdRouteWithChildren
  '/api/v1/setup/charts': typeof ApiV1SetupChartsRoute
  '/api/v1/vat/filings': typeof ApiV1VatFilingsRoute
  '/api/v1/vat/number-checks': typeof ApiV1VatNumberChecksRoute
  '/api/v1/vat/periods': typeof ApiV1VatPeriodsRoute
  '/api/v1/bank-transactions/$transactionId/ignore': typeof ApiV1BankTransactionsTransactionIdIgnoreRoute
  '/api/v1/bank-transactions/$transactionId/match': typeof ApiV1BankTransactionsTransactionIdMatchRoute
  '/api/v1/bank-transactions/$transactionId/suggestions': typeof ApiV1BankTransactionsTransactionIdSuggestionsRoute
  '/api/v1/journal-entries/$entryId/reversal': typeof ApiV1JournalEntriesEntryIdReversalRoute
  '/api/v1/payment-batches/$batchId/instructions': typeof ApiV1PaymentBatchesBatchIdInstructionsRouteWithChildren
  '/api/v1/payment-batches/$batchId/pain001': typeof ApiV1PaymentBatchesBatchIdPain001Route
  '/api/v1/payment-batches/$batchId/transitions': typeof ApiV1PaymentBatchesBatchIdTransitionsRoute
  '/api/v1/sales-invoices/$invoiceId/deliveries': typeof ApiV1SalesInvoicesInvoiceIdDeliveriesRoute
  '/api/v1/sales-invoices/$invoiceId/issue': typeof ApiV1SalesInvoicesInvoiceIdIssueRoute
  '/api/v1/sales-invoices/$invoiceId/pdf': typeof ApiV1SalesInvoicesInvoiceIdPdfRoute
  '/api/v1/sales-invoices/$invoiceId/reminders': typeof ApiV1SalesInvoicesInvoiceIdRemindersRoute
  '/api/v1/sales-invoices/$invoiceId/send': typeof ApiV1SalesInvoicesInvoiceIdSendRoute
  '/api/v1/sales-invoices/$invoiceId/ubl': typeof ApiV1SalesInvoicesInvoiceIdUblRoute
  '/api/v1/vat/icp/$period': typeof ApiV1VatIcpPeriodRoute
  '/api/v1/vat/returns/$period': typeof ApiV1VatReturnsPeriodRoute
  '/api/v1/payment-batches/$batchId/instructions/$instructionId': typeof ApiV1PaymentBatchesBatchIdInstructionsInstructionIdRoute
}
export interface FileRoutesByTo {
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/accounts': typeof AppAccountsRoute
  '/contacts': typeof AppContactsRoute
  '/dunning': typeof AppDunningRoute
  '/members': typeof AppMembersRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/bank/match': typeof AppBankMatchRoute
  '/entries/$entryId': typeof AppEntriesEntryIdRoute
  '/entries/new': typeof AppEntriesNewRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/payments/$batchId': typeof AppPaymentsBatchIdRoute
  '/reports/balance-sheet': typeof AppReportsBalanceSheetRoute
  '/reports/profit-and-loss': typeof AppReportsProfitAndLossRoute
  '/reports/trial-balance': typeof AppReportsTrialBalanceRoute
  '/vat/$period': typeof AppVatPeriodRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/accounts': typeof ApiV1AccountsRoute
  '/api/v1/bank-accounts': typeof ApiV1BankAccountsRoute
  '/api/v1/bank-match-rules': typeof ApiV1BankMatchRulesRouteWithChildren
  '/api/v1/bank-statements': typeof ApiV1BankStatementsRoute
  '/api/v1/bank-transactions': typeof ApiV1BankTransactionsRouteWithChildren
  '/api/v1/contacts': typeof ApiV1ContactsRoute
  '/api/v1/entity': typeof ApiV1EntityRoute
  '/api/v1/fiscal-years': typeof ApiV1FiscalYearsRouteWithChildren
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/journal-entries': typeof ApiV1JournalEntriesRouteWithChildren
  '/api/v1/members': typeof ApiV1MembersRouteWithChildren
  '/api/v1/payment-batches': typeof ApiV1PaymentBatchesRouteWithChildren
  '/api/v1/sales-invoices': typeof ApiV1SalesInvoicesRouteWithChildren
  '/api/v1/tax-codes': typeof ApiV1TaxCodesRoute
  '/bank': typeof AppBankIndexRoute
  '/entries': typeof AppEntriesIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/payments': typeof AppPaymentsIndexRoute
  '/vat': typeof AppVatIndexRoute
  '/vat/icp/$period': typeof AppVatIcpPeriodRoute
  '/api/v1/bank-match-rules/$ruleId': typeof ApiV1BankMatchRulesRuleIdRoute
  '/api/v1/entities/$entityId': typeof ApiV1EntitiesEntityIdRoute
  '/api/v1/exports/audit-file': typeof ApiV1ExportsAuditFileRoute
  '/api/v1/fiscal-years/close': typeof ApiV1FiscalYearsCloseRoute
  '/api/v1/imports/audit-file': typeof ApiV1ImportsAuditFileRoute
  '/api/v1/journal-entries/$entryId': typeof ApiV1JournalEntriesEntryIdRouteWithChildren
  '/api/v1/ledger/chain-verification': typeof ApiV1LedgerChainVerificationRoute
  '/api/v1/members/$memberId': typeof ApiV1MembersMemberIdRoute
  '/api/v1/payment-batches/$batchId': typeof ApiV1PaymentBatchesBatchIdRouteWithChildren
  '/api/v1/reports/balance-sheet': typeof ApiV1ReportsBalanceSheetRoute
  '/api/v1/reports/dunning': typeof ApiV1ReportsDunningRoute
  '/api/v1/reports/overdue-invoices': typeof ApiV1ReportsOverdueInvoicesRoute
  '/api/v1/reports/profit-and-loss': typeof ApiV1ReportsProfitAndLossRoute
  '/api/v1/reports/trial-balance': typeof ApiV1ReportsTrialBalanceRoute
  '/api/v1/rgs/coverage': typeof ApiV1RgsCoverageRoute
  '/api/v1/rgs/mappings': typeof ApiV1RgsMappingsRoute
  '/api/v1/rgs/upgrade-preview': typeof ApiV1RgsUpgradePreviewRoute
  '/api/v1/sales-invoices/$invoiceId': typeof ApiV1SalesInvoicesInvoiceIdRouteWithChildren
  '/api/v1/setup/charts': typeof ApiV1SetupChartsRoute
  '/api/v1/vat/filings': typeof ApiV1VatFilingsRoute
  '/api/v1/vat/number-checks': typeof ApiV1VatNumberChecksRoute
  '/api/v1/vat/periods': typeof ApiV1VatPeriodsRoute
  '/api/v1/bank-transactions/$transactionId/ignore': typeof ApiV1BankTransactionsTransactionIdIgnoreRoute
  '/api/v1/bank-transactions/$transactionId/match': typeof ApiV1BankTransactionsTransactionIdMatchRoute
  '/api/v1/bank-transactions/$transactionId/suggestions': typeof ApiV1BankTransactionsTransactionIdSuggestionsRoute
  '/api/v1/journal-entries/$entryId/reversal': typeof ApiV1JournalEntriesEntryIdReversalRoute
  '/api/v1/payment-batches/$batchId/instructions': typeof ApiV1PaymentBatchesBatchIdInstructionsRouteWithChildren
  '/api/v1/payment-batches/$batchId/pain001': typeof ApiV1PaymentBatchesBatchIdPain001Route
  '/api/v1/payment-batches/$batchId/transitions': typeof ApiV1PaymentBatchesBatchIdTransitionsRoute
  '/api/v1/sales-invoices/$invoiceId/deliveries': typeof ApiV1SalesInvoicesInvoiceIdDeliveriesRoute
  '/api/v1/sales-invoices/$invoiceId/issue': typeof ApiV1SalesInvoicesInvoiceIdIssueRoute
  '/api/v1/sales-invoices/$invoiceId/pdf': typeof ApiV1SalesInvoicesInvoiceIdPdfRoute
  '/api/v1/sales-invoices/$invoiceId/reminders': typeof ApiV1SalesInvoicesInvoiceIdRemindersRoute
  '/api/v1/sales-invoices/$invoiceId/send': typeof ApiV1SalesInvoicesInvoiceIdSendRoute
  '/api/v1/sales-invoices/$invoiceId/ubl': typeof ApiV1SalesInvoicesInvoiceIdUblRoute
  '/api/v1/vat/icp/$period': typeof ApiV1VatIcpPeriodRoute
  '/api/v1/vat/returns/$period': typeof ApiV1VatReturnsPeriodRoute
  '/api/v1/payment-batches/$batchId/instructions/$instructionId': typeof ApiV1PaymentBatchesBatchIdInstructionsInstructionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/setup': typeof SetupRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/dunning': typeof AppDunningRoute
  '/_app/members': typeof AppMembersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/bank/match': typeof AppBankMatchRoute
  '/_app/entries/$entryId': typeof AppEntriesEntryIdRoute
  '/_app/entries/new': typeof AppEntriesNewRoute
  '/_app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/_app/invoices/new': typeof AppInvoicesNewRoute
  '/_app/payments/$batchId': typeof AppPaymentsBatchIdRoute
  '/_app/reports/balance-sheet': typeof AppReportsBalanceSheetRoute
  '/_app/reports/profit-and-loss': typeof AppReportsProfitAndLossRoute
  '/_app/reports/trial-balance': typeof AppReportsTrialBalanceRoute
  '/_app/vat/$period': typeof AppVatPeriodRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/accounts': typeof ApiV1AccountsRoute
  '/api/v1/bank-accounts': typeof ApiV1BankAccountsRoute
  '/api/v1/bank-match-rules': typeof ApiV1BankMatchRulesRouteWithChildren
  '/api/v1/bank-statements': typeof ApiV1BankStatementsRoute
  '/api/v1/bank-transactions': typeof ApiV1BankTransactionsRouteWithChildren
  '/api/v1/contacts': typeof ApiV1ContactsRoute
  '/api/v1/entity': typeof ApiV1EntityRoute
  '/api/v1/fiscal-years': typeof ApiV1FiscalYearsRouteWithChildren
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/journal-entries': typeof ApiV1JournalEntriesRouteWithChildren
  '/api/v1/members': typeof ApiV1MembersRouteWithChildren
  '/api/v1/payment-batches': typeof ApiV1PaymentBatchesRouteWithChildren
  '/api/v1/sales-invoices': typeof ApiV1SalesInvoicesRouteWithChildren
  '/api/v1/tax-codes': typeof ApiV1TaxCodesRoute
  '/_app/bank/': typeof AppBankIndexRoute
  '/_app/entries/': typeof AppEntriesIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/payments/': typeof AppPaymentsIndexRoute
  '/_app/vat/': typeof AppVatIndexRoute
  '/_app/vat/icp/$period': typeof AppVatIcpPeriodRoute
  '/api/v1/bank-match-rules/$ruleId': typeof ApiV1BankMatchRulesRuleIdRoute
  '/api/v1/entities/$entityId': typeof ApiV1EntitiesEntityIdRoute
  '/api/v1/exports/audit-file': typeof ApiV1ExportsAuditFileRoute
  '/api/v1/fiscal-years/close': typeof ApiV1FiscalYearsCloseRoute
  '/api/v1/imports/audit-file': typeof ApiV1ImportsAuditFileRoute
  '/api/v1/journal-entries/$entryId': typeof ApiV1JournalEntriesEntryIdRouteWithChildren
  '/api/v1/ledger/chain-verification': typeof ApiV1LedgerChainVerificationRoute
  '/api/v1/members/$memberId': typeof ApiV1MembersMemberIdRoute
  '/api/v1/payment-batches/$batchId': typeof ApiV1PaymentBatchesBatchIdRouteWithChildren
  '/api/v1/reports/balance-sheet': typeof ApiV1ReportsBalanceSheetRoute
  '/api/v1/reports/dunning': typeof ApiV1ReportsDunningRoute
  '/api/v1/reports/overdue-invoices': typeof ApiV1ReportsOverdueInvoicesRoute
  '/api/v1/reports/profit-and-loss': typeof ApiV1ReportsProfitAndLossRoute
  '/api/v1/reports/trial-balance': typeof ApiV1ReportsTrialBalanceRoute
  '/api/v1/rgs/coverage': typeof ApiV1RgsCoverageRoute
  '/api/v1/rgs/mappings': typeof ApiV1RgsMappingsRoute
  '/api/v1/rgs/upgrade-preview': typeof ApiV1RgsUpgradePreviewRoute
  '/api/v1/sales-invoices/$invoiceId': typeof ApiV1SalesInvoicesInvoiceIdRouteWithChildren
  '/api/v1/setup/charts': typeof ApiV1SetupChartsRoute
  '/api/v1/vat/filings': typeof ApiV1VatFilingsRoute
  '/api/v1/vat/number-checks': typeof ApiV1VatNumberChecksRoute
  '/api/v1/vat/periods': typeof ApiV1VatPeriodsRoute
  '/api/v1/bank-transactions/$transactionId/ignore': typeof ApiV1BankTransactionsTransactionIdIgnoreRoute
  '/api/v1/bank-transactions/$transactionId/match': typeof ApiV1BankTransactionsTransactionIdMatchRoute
  '/api/v1/bank-transactions/$transactionId/suggestions': typeof ApiV1BankTransactionsTransactionIdSuggestionsRoute
  '/api/v1/journal-entries/$entryId/reversal': typeof ApiV1JournalEntriesEntryIdReversalRoute
  '/api/v1/payment-batches/$batchId/instructions': typeof ApiV1PaymentBatchesBatchIdInstructionsRouteWithChildren
  '/api/v1/payment-batches/$batchId/pain001': typeof ApiV1PaymentBatchesBatchIdPain001Route
  '/api/v1/payment-batches/$batchId/transitions': typeof ApiV1PaymentBatchesBatchIdTransitionsRoute
  '/api/v1/sales-invoices/$invoiceId/deliveries': typeof ApiV1SalesInvoicesInvoiceIdDeliveriesRoute
  '/api/v1/sales-invoices/$invoiceId/issue': typeof ApiV1SalesInvoicesInvoiceIdIssueRoute
  '/api/v1/sales-invoices/$invoiceId/pdf': typeof ApiV1SalesInvoicesInvoiceIdPdfRoute
  '/api/v1/sales-invoices/$invoiceId/reminders': typeof ApiV1SalesInvoicesInvoiceIdRemindersRoute
  '/api/v1/sales-invoices/$invoiceId/send': typeof ApiV1SalesInvoicesInvoiceIdSendRoute
  '/api/v1/sales-invoices/$invoiceId/ubl': typeof ApiV1SalesInvoicesInvoiceIdUblRoute
  '/api/v1/vat/icp/$period': typeof ApiV1VatIcpPeriodRoute
  '/api/v1/vat/returns/$period': typeof ApiV1VatReturnsPeriodRoute
  '/api/v1/payment-batches/$batchId/instructions/$instructionId': typeof ApiV1PaymentBatchesBatchIdInstructionsInstructionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/sign-in'
    | '/sign-out'
    | '/accounts'
    | '/contacts'
    | '/dunning'
    | '/members'
    | '/settings'
    | '/bank/match'
    | '/entries/$entryId'
    | '/entries/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/payments/$batchId'
    | '/reports/balance-sheet'
    | '/reports/profit-and-loss'
    | '/reports/trial-balance'
    | '/vat/$period'
    | '/api/auth/$'
    | '/api/v1/accounts'
    | '/api/v1/bank-accounts'
    | '/api/v1/bank-match-rules'
    | '/api/v1/bank-statements'
    | '/api/v1/bank-transactions'
    | '/api/v1/contacts'
    | '/api/v1/entity'
    | '/api/v1/fiscal-years'
    | '/api/v1/health'
    | '/api/v1/journal-entries'
    | '/api/v1/members'
    | '/api/v1/payment-batches'
    | '/api/v1/sales-invoices'
    | '/api/v1/tax-codes'
    | '/bank/'
    | '/entries/'
    | '/invoices/'
    | '/payments/'
    | '/vat/'
    | '/vat/icp/$period'
    | '/api/v1/bank-match-rules/$ruleId'
    | '/api/v1/entities/$entityId'
    | '/api/v1/exports/audit-file'
    | '/api/v1/fiscal-years/close'
    | '/api/v1/imports/audit-file'
    | '/api/v1/journal-entries/$entryId'
    | '/api/v1/ledger/chain-verification'
    | '/api/v1/members/$memberId'
    | '/api/v1/payment-batches/$batchId'
    | '/api/v1/reports/balance-sheet'
    | '/api/v1/reports/dunning'
    | '/api/v1/reports/overdue-invoices'
    | '/api/v1/reports/profit-and-loss'
    | '/api/v1/reports/trial-balance'
    | '/api/v1/rgs/coverage'
    | '/api/v1/rgs/mappings'
    | '/api/v1/rgs/upgrade-preview'
    | '/api/v1/sales-invoices/$invoiceId'
    | '/api/v1/setup/charts'
    | '/api/v1/vat/filings'
    | '/api/v1/vat/number-checks'
    | '/api/v1/vat/periods'
    | '/api/v1/bank-transactions/$transactionId/ignore'
    | '/api/v1/bank-transactions/$transactionId/match'
    | '/api/v1/bank-transactions/$transactionId/suggestions'
    | '/api/v1/journal-entries/$entryId/reversal'
    | '/api/v1/payment-batches/$batchId/instructions'
    | '/api/v1/payment-batches/$batchId/pain001'
    | '/api/v1/payment-batches/$batchId/transitions'
    | '/api/v1/sales-invoices/$invoiceId/deliveries'
    | '/api/v1/sales-invoices/$invoiceId/issue'
    | '/api/v1/sales-invoices/$invoiceId/pdf'
    | '/api/v1/sales-invoices/$invoiceId/reminders'
    | '/api/v1/sales-invoices/$invoiceId/send'
    | '/api/v1/sales-invoices/$invoiceId/ubl'
    | '/api/v1/vat/icp/$period'
    | '/api/v1/vat/returns/$period'
    | '/api/v1/payment-batches/$batchId/instructions/$instructionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/sign-in'
    | '/sign-out'
    | '/accounts'
    | '/contacts'
    | '/dunning'
    | '/members'
    | '/settings'
    | '/'
    | '/bank/match'
    | '/entries/$entryId'
    | '/entries/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/payments/$batchId'
    | '/reports/balance-sheet'
    | '/reports/profit-and-loss'
    | '/reports/trial-balance'
    | '/vat/$period'
    | '/api/auth/$'
    | '/api/v1/accounts'
    | '/api/v1/bank-accounts'
    | '/api/v1/bank-match-rules'
    | '/api/v1/bank-statements'
    | '/api/v1/bank-transactions'
    | '/api/v1/contacts'
    | '/api/v1/entity'
    | '/api/v1/fiscal-years'
    | '/api/v1/health'
    | '/api/v1/journal-entries'
    | '/api/v1/members'
    | '/api/v1/payment-batches'
    | '/api/v1/sales-invoices'
    | '/api/v1/tax-codes'
    | '/bank'
    | '/entries'
    | '/invoices'
    | '/payments'
    | '/vat'
    | '/vat/icp/$period'
    | '/api/v1/bank-match-rules/$ruleId'
    | '/api/v1/entities/$entityId'
    | '/api/v1/exports/audit-file'
    | '/api/v1/fiscal-years/close'
    | '/api/v1/imports/audit-file'
    | '/api/v1/journal-entries/$entryId'
    | '/api/v1/ledger/chain-verification'
    | '/api/v1/members/$memberId'
    | '/api/v1/payment-batches/$batchId'
    | '/api/v1/reports/balance-sheet'
    | '/api/v1/reports/dunning'
    | '/api/v1/reports/overdue-invoices'
    | '/api/v1/reports/profit-and-loss'
    | '/api/v1/reports/trial-balance'
    | '/api/v1/rgs/coverage'
    | '/api/v1/rgs/mappings'
    | '/api/v1/rgs/upgrade-preview'
    | '/api/v1/sales-invoices/$invoiceId'
    | '/api/v1/setup/charts'
    | '/api/v1/vat/filings'
    | '/api/v1/vat/number-checks'
    | '/api/v1/vat/periods'
    | '/api/v1/bank-transactions/$transactionId/ignore'
    | '/api/v1/bank-transactions/$transactionId/match'
    | '/api/v1/bank-transactions/$transactionId/suggestions'
    | '/api/v1/journal-entries/$entryId/reversal'
    | '/api/v1/payment-batches/$batchId/instructions'
    | '/api/v1/payment-batches/$batchId/pain001'
    | '/api/v1/payment-batches/$batchId/transitions'
    | '/api/v1/sales-invoices/$invoiceId/deliveries'
    | '/api/v1/sales-invoices/$invoiceId/issue'
    | '/api/v1/sales-invoices/$invoiceId/pdf'
    | '/api/v1/sales-invoices/$invoiceId/reminders'
    | '/api/v1/sales-invoices/$invoiceId/send'
    | '/api/v1/sales-invoices/$invoiceId/ubl'
    | '/api/v1/vat/icp/$period'
    | '/api/v1/vat/returns/$period'
    | '/api/v1/payment-batches/$batchId/instructions/$instructionId'
  id:
    | '__root__'
    | '/_app'
    | '/setup'
    | '/sign-in'
    | '/sign-out'
    | '/_app/accounts'
    | '/_app/contacts'
    | '/_app/dunning'
    | '/_app/members'
    | '/_app/settings'
    | '/_app/'
    | '/_app/bank/match'
    | '/_app/entries/$entryId'
    | '/_app/entries/new'
    | '/_app/invoices/$invoiceId'
    | '/_app/invoices/new'
    | '/_app/payments/$batchId'
    | '/_app/reports/balance-sheet'
    | '/_app/reports/profit-and-loss'
    | '/_app/reports/trial-balance'
    | '/_app/vat/$period'
    | '/api/auth/$'
    | '/api/v1/accounts'
    | '/api/v1/bank-accounts'
    | '/api/v1/bank-match-rules'
    | '/api/v1/bank-statements'
    | '/api/v1/bank-transactions'
    | '/api/v1/contacts'
    | '/api/v1/entity'
    | '/api/v1/fiscal-years'
    | '/api/v1/health'
    | '/api/v1/journal-entries'
    | '/api/v1/members'
    | '/api/v1/payment-batches'
    | '/api/v1/sales-invoices'
    | '/api/v1/tax-codes'
    | '/_app/bank/'
    | '/_app/entries/'
    | '/_app/invoices/'
    | '/_app/payments/'
    | '/_app/vat/'
    | '/_app/vat/icp/$period'
    | '/api/v1/bank-match-rules/$ruleId'
    | '/api/v1/entities/$entityId'
    | '/api/v1/exports/audit-file'
    | '/api/v1/fiscal-years/close'
    | '/api/v1/imports/audit-file'
    | '/api/v1/journal-entries/$entryId'
    | '/api/v1/ledger/chain-verification'
    | '/api/v1/members/$memberId'
    | '/api/v1/payment-batches/$batchId'
    | '/api/v1/reports/balance-sheet'
    | '/api/v1/reports/dunning'
    | '/api/v1/reports/overdue-invoices'
    | '/api/v1/reports/profit-and-loss'
    | '/api/v1/reports/trial-balance'
    | '/api/v1/rgs/coverage'
    | '/api/v1/rgs/mappings'
    | '/api/v1/rgs/upgrade-preview'
    | '/api/v1/sales-invoices/$invoiceId'
    | '/api/v1/setup/charts'
    | '/api/v1/vat/filings'
    | '/api/v1/vat/number-checks'
    | '/api/v1/vat/periods'
    | '/api/v1/bank-transactions/$transactionId/ignore'
    | '/api/v1/bank-transactions/$transactionId/match'
    | '/api/v1/bank-transactions/$transactionId/suggestions'
    | '/api/v1/journal-entries/$entryId/reversal'
    | '/api/v1/payment-batches/$batchId/instructions'
    | '/api/v1/payment-batches/$batchId/pain001'
    | '/api/v1/payment-batches/$batchId/transitions'
    | '/api/v1/sales-invoices/$invoiceId/deliveries'
    | '/api/v1/sales-invoices/$invoiceId/issue'
    | '/api/v1/sales-invoices/$invoiceId/pdf'
    | '/api/v1/sales-invoices/$invoiceId/reminders'
    | '/api/v1/sales-invoices/$invoiceId/send'
    | '/api/v1/sales-invoices/$invoiceId/ubl'
    | '/api/v1/vat/icp/$period'
    | '/api/v1/vat/returns/$period'
    | '/api/v1/payment-batches/$batchId/instructions/$instructionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SetupRoute: typeof SetupRoute
  SignInRoute: typeof SignInRoute
  SignOutRoute: typeof SignOutRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1AccountsRoute: typeof ApiV1AccountsRoute
  ApiV1BankAccountsRoute: typeof ApiV1BankAccountsRoute
  ApiV1BankMatchRulesRoute: typeof ApiV1BankMatchRulesRouteWithChildren
  ApiV1BankStatementsRoute: typeof ApiV1BankStatementsRoute
  ApiV1BankTransactionsRoute: typeof ApiV1BankTransactionsRouteWithChildren
  ApiV1ContactsRoute: typeof ApiV1ContactsRoute
  ApiV1EntityRoute: typeof ApiV1EntityRoute
  ApiV1FiscalYearsRoute: typeof ApiV1FiscalYearsRouteWithChildren
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1JournalEntriesRoute: typeof ApiV1JournalEntriesRouteWithChildren
  ApiV1MembersRoute: typeof ApiV1MembersRouteWithChildren
  ApiV1PaymentBatchesRoute: typeof ApiV1PaymentBatchesRouteWithChildren
  ApiV1SalesInvoicesRoute: typeof ApiV1SalesInvoicesRouteWithChildren
  ApiV1TaxCodesRoute: typeof ApiV1TaxCodesRoute
  ApiV1EntitiesEntityIdRoute: typeof ApiV1EntitiesEntityIdRoute
  ApiV1ExportsAuditFileRoute: typeof ApiV1ExportsAuditFileRoute
  ApiV1ImportsAuditFileRoute: typeof ApiV1ImportsAuditFileRoute
  ApiV1LedgerChainVerificationRoute: typeof ApiV1LedgerChainVerificationRoute
  ApiV1ReportsBalanceSheetRoute: typeof ApiV1ReportsBalanceSheetRoute
  ApiV1ReportsDunningRoute: typeof ApiV1ReportsDunningRoute
  ApiV1ReportsOverdueInvoicesRoute: typeof ApiV1ReportsOverdueInvoicesRoute
  ApiV1ReportsProfitAndLossRoute: typeof ApiV1ReportsProfitAndLossRoute
  ApiV1ReportsTrialBalanceRoute: typeof ApiV1ReportsTrialBalanceRoute
  ApiV1RgsCoverageRoute: typeof ApiV1RgsCoverageRoute
  ApiV1RgsMappingsRoute: typeof ApiV1RgsMappingsRoute
  ApiV1RgsUpgradePreviewRoute: typeof ApiV1RgsUpgradePreviewRoute
  ApiV1SetupChartsRoute: typeof ApiV1SetupChartsRoute
  ApiV1VatFilingsRoute: typeof ApiV1VatFilingsRoute
  ApiV1VatNumberChecksRoute: typeof ApiV1VatNumberChecksRoute
  ApiV1VatPeriodsRoute: typeof ApiV1VatPeriodsRoute
  ApiV1VatIcpPeriodRoute: typeof ApiV1VatIcpPeriodRoute
  ApiV1VatReturnsPeriodRoute: typeof ApiV1VatReturnsPeriodRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dunning': {
      id: '/_app/dunning'
      path: '/dunning'
      fullPath: '/dunning'
      preLoaderRoute: typeof AppDunningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members': {
      id: '/_app/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank/': {
      id: '/_app/bank/'
      path: '/bank'
      fullPath: '/bank/'
      preLoaderRoute: typeof AppBankIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank/match': {
      id: '/_app/bank/match'
      path: '/bank/match'
      fullPath: '/bank/match'
      preLoaderRoute: typeof AppBankMatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entries/': {
      id: '/_app/entries/'
      path: '/entries'
      fullPath: '/entries/'
      preLoaderRoute: typeof AppEntriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entries/$entryId': {
      id: '/_app/entries/$entryId'
      path: '/entries/$entryId'
      fullPath: '/entries/$entryId'
      preLoaderRoute: typeof AppEntriesEntryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entries/new': {
      id: '/_app/entries/new'
      path: '/entries/new'
      fullPath: '/entries/new'
      preLoaderRoute: typeof AppEntriesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$invoiceId': {
      id: '/_app/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/new': {
      id: '/_app/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/': {
      id: '/_app/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AppPaymentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/$batchId': {
      id: '/_app/payments/$batchId'
      path: '/payments/$batchId'
      fullPath: '/payments/$batchId'
      preLoaderRoute: typeof AppPaymentsBatchIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/balance-sheet': {
      id: '/_app/reports/balance-sheet'
      path: '/reports/balance-sheet'
      fullPath: '/reports/balance-sheet'
      preLoaderRoute: typeof AppReportsBalanceSheetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/profit-and-loss': {
      id: '/_app/reports/profit-and-loss'
      path: '/reports/profit-and-loss'
      fullPath: '/reports/profit-and-loss'
      preLoaderRoute: typeof AppReportsProfitAndLossRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/trial-balance': {
      id: '/_app/reports/trial-balance'
      path: '/reports/trial-balance'
      fullPath: '/reports/trial-balance'
      preLoaderRoute: typeof AppReportsTrialBalanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vat/': {
      id: '/_app/vat/'
      path: '/vat'
      fullPath: '/vat/'
      preLoaderRoute: typeof AppVatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vat/$period': {
      id: '/_app/vat/$period'
      path: '/vat/$period'
      fullPath: '/vat/$period'
      preLoaderRoute: typeof AppVatPeriodRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts': {
      id: '/api/v1/accounts'
      path: '/api/v1/accounts'
      fullPath: '/api/v1/accounts'
      preLoaderRoute: typeof ApiV1AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/bank-accounts': {
      id: '/api/v1/bank-accounts'
      path: '/api/v1/bank-accounts'
      fullPath: '/api/v1/bank-accounts'
      preLoaderRoute: typeof ApiV1BankAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/bank-match-rules': {
      id: '/api/v1/bank-match-rules'
      path: '/api/v1/bank-match-rules'
      fullPath: '/api/v1/bank-match-rules'
      preLoaderRoute: typeof ApiV1BankMatchRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/bank-statements': {
      id: '/api/v1/bank-statements'
      path: '/api/v1/bank-statements'
      fullPath: '/api/v1/bank-statements'
      preLoaderRoute: typeof ApiV1BankStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/bank-transactions': {
      id: '/api/v1/bank-transactions'
      path: '/api/v1/bank-transactions'
      fullPath: '/api/v1/bank-transactions'
      preLoaderRoute: typeof ApiV1BankTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/contacts': {
      id: '/api/v1/contacts'
      path: '/api/v1/contacts'
      fullPath: '/api/v1/contacts'
      preLoaderRoute: typeof ApiV1ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/entity': {
      id: '/api/v1/entity'
      path: '/api/v1/entity'
      fullPath: '/api/v1/entity'
      preLoaderRoute: typeof ApiV1EntityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/fiscal-years': {
      id: '/api/v1/fiscal-years'
      path: '/api/v1/fiscal-years'
      fullPath: '/api/v1/fiscal-years'
      preLoaderRoute: typeof ApiV1FiscalYearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/journal-entries': {
      id: '/api/v1/journal-entries'
      path: '/api/v1/journal-entries'
      fullPath: '/api/v1/journal-entries'
      preLoaderRoute: typeof ApiV1JournalEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/members': {
      id: '/api/v1/members'
      path: '/api/v1/members'
      fullPath: '/api/v1/members'
      preLoaderRoute: typeof ApiV1MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/payment-batches': {
      id: '/api/v1/payment-batches'
      path: '/api/v1/payment-batches'
      fullPath: '/api/v1/payment-batches'
      preLoaderRoute: typeof ApiV1PaymentBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sales-invoices': {
      id: '/api/v1/sales-invoices'
      path: '/api/v1/sales-invoices'
      fullPath: '/api/v1/sales-invoices'
      preLoaderRoute: typeof ApiV1SalesInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tax-codes': {
      id: '/api/v1/tax-codes'
      path: '/api/v1/tax-codes'
      fullPath: '/api/v1/tax-codes'
      preLoaderRoute: typeof ApiV1TaxCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vat/icp/$period': {
      id: '/_app/vat/icp/$period'
      path: '/vat/icp/$period'
      fullPath: '/vat/icp/$period'
      preLoaderRoute: typeof AppVatIcpPeriodRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1/bank-match-rules/$ruleId': {
      id: '/api/v1/bank-match-rules/$ruleId'
      path: '/$ruleId'
      fullPath: '/api/v1/bank-match-rules/$ruleId'
      preLoaderRoute: typeof ApiV1BankMatchRulesRuleIdRouteImport
      parentRoute: typeof ApiV1BankMatchRulesRoute
    }
    '/api/v1/entities/$entityId': {
      id: '/api/v1/entities/$entityId'
      path: '/api/v1/entities/$entityId'
      fullPath: '/api/v1/entities/$entityId'
      preLoaderRoute: typeof ApiV1EntitiesEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/exports/audit-file': {
      id: '/api/v1/exports/audit-file'
      path: '/api/v1/exports/audit-file'
      fullPath: '/api/v1/exports/audit-file'
      preLoaderRoute: typeof ApiV1ExportsAuditFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/fiscal-years/close': {
      id: '/api/v1/fiscal-years/close'
      path: '/close'
      fullPath: '/api/v1/fiscal-years/close'
      preLoaderRoute: typeof ApiV1FiscalYearsCloseRouteImport
      parentRoute: typeof ApiV1FiscalYearsRoute
    }
    '/api/v1/imports/audit-file': {
      id: '/api/v1/imports/audit-file'
      path: '/api/v1/imports/audit-file'
      fullPath: '/api/v1/imports/audit-file'
      preLoaderRoute: typeof ApiV1ImportsAuditFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/journal-entries/$entryId': {
      id: '/api/v1/journal-entries/$entryId'
      path: '/$entryId'
      fullPath: '/api/v1/journal-entries/$entryId'
      preLoaderRoute: typeof ApiV1JournalEntriesEntryIdRouteImport
      parentRoute: typeof ApiV1JournalEntriesRoute
    }
    '/api/v1/ledger/chain-verification': {
      id: '/api/v1/ledger/chain-verification'
      path: '/api/v1/ledger/chain-verification'
      fullPath: '/api/v1/ledger/chain-verification'
      preLoaderRoute: typeof ApiV1LedgerChainVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/members/$memberId': {
      id: '/api/v1/members/$memberId'
      path: '/$memberId'
      fullPath: '/api/v1/members/$memberId'
      preLoaderRoute: typeof ApiV1MembersMemberIdRouteImport
      parentRoute: typeof ApiV1MembersRoute
    }
    '/api/v1/payment-batches/$batchId': {
      id: '/api/v1/payment-batches/$batchId'
      path: '/$batchId'
      fullPath: '/api/v1/payment-batches/$batchId'
      preLoaderRoute: typeof ApiV1PaymentBatchesBatchIdRouteImport
      parentRoute: typeof ApiV1PaymentBatchesRoute
    }
    '/api/v1/reports/balance-sheet': {
      id: '/api/v1/reports/balance-sheet'
      path: '/api/v1/reports/balance-sheet'
      fullPath: '/api/v1/reports/balance-sheet'
      preLoaderRoute: typeof ApiV1ReportsBalanceSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports/dunning': {
      id: '/api/v1/reports/dunning'
      path: '/api/v1/reports/dunning'
      fullPath: '/api/v1/reports/dunning'
      preLoaderRoute: typeof ApiV1ReportsDunningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports/overdue-invoices': {
      id: '/api/v1/reports/overdue-invoices'
      path: '/api/v1/reports/overdue-invoices'
      fullPath: '/api/v1/reports/overdue-invoices'
      preLoaderRoute: typeof ApiV1ReportsOverdueInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports/profit-and-loss': {
      id: '/api/v1/reports/profit-and-loss'
      path: '/api/v1/reports/profit-and-loss'
      fullPath: '/api/v1/reports/profit-and-loss'
      preLoaderRoute: typeof ApiV1ReportsProfitAndLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports/trial-balance': {
      id: '/api/v1/reports/trial-balance'
      path: '/api/v1/reports/trial-balance'
      fullPath: '/api/v1/reports/trial-balance'
      preLoaderRoute: typeof ApiV1ReportsTrialBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/rgs/coverage': {
      id: '/api/v1/rgs/coverage'
      path: '/api/v1/rgs/coverage'
      fullPath: '/api/v1/rgs/coverage'
      preLoaderRoute: typeof ApiV1RgsCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/rgs/mappings': {
      id: '/api/v1/rgs/mappings'
      path: '/api/v1/rgs/mappings'
      fullPath: '/api/v1/rgs/mappings'
      preLoaderRoute: typeof ApiV1RgsMappingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/rgs/upgrade-preview': {
      id: '/api/v1/rgs/upgrade-preview'
      path: '/api/v1/rgs/upgrade-preview'
      fullPath: '/api/v1/rgs/upgrade-preview'
      preLoaderRoute: typeof ApiV1RgsUpgradePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sales-invoices/$invoiceId': {
      id: '/api/v1/sales-invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/api/v1/sales-invoices/$invoiceId'
      preLoaderRoute: typeof ApiV1SalesInvoicesInvoiceIdRouteImport
      parentRoute: typeof ApiV1SalesInvoicesRoute
    }
    '/api/v1/setup/charts': {
      id: '/api/v1/setup/charts'
      path: '/api/v1/setup/charts'
      fullPath: '/api/v1/setup/charts'
      preLoaderRoute: typeof ApiV1SetupChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/vat/filings': {
      id: '/api/v1/vat/filings'
      path: '/api/v1/vat/filings'
      fullPath: '/api/v1/vat/filings'
      preLoaderRoute: typeof ApiV1VatFilingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/vat/number-checks': {
      id: '/api/v1/vat/number-checks'
      path: '/api/v1/vat/number-checks'
      fullPath: '/api/v1/vat/number-checks'
      preLoaderRoute: typeof ApiV1VatNumberChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/vat/periods': {
      id: '/api/v1/vat/periods'
      path: '/api/v1/vat/periods'
      fullPath: '/api/v1/vat/periods'
      preLoaderRoute: typeof ApiV1VatPeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/bank-transactions/$transactionId/ignore': {
      id: '/api/v1/bank-transactions/$transactionId/ignore'
      path: '/$transactionId/ignore'
      fullPath: '/api/v1/bank-transactions/$transactionId/ignore'
      preLoaderRoute: typeof ApiV1BankTransactionsTransactionIdIgnoreRouteImport
      parentRoute: typeof ApiV1BankTransactionsRoute
    }
    '/api/v1/bank-transactions/$transactionId/match': {
      id: '/api/v1/bank-transactions/$transactionId/match'
      path: '/$transactionId/match'
      fullPath: '/api/v1/bank-transactions/$transactionId/match'
      preLoaderRoute: typeof ApiV1BankTransactionsTransactionIdMatchRouteImport
      parentRoute: typeof ApiV1BankTransactionsRoute
    }
    '/api/v1/bank-transactions/$transactionId/suggestions': {
      id: '/api/v1/bank-transactions/$transactionId/suggestions'
      path: '/$transactionId/suggestions'
      fullPath: '/api/v1/bank-transactions/$transactionId/suggestions'
      preLoaderRoute: typeof ApiV1BankTransactionsTransactionIdSuggestionsRouteImport
      parentRoute: typeof ApiV1BankTransactionsRoute
    }
    '/api/v1/journal-entries/$entryId/reversal': {
      id: '/api/v1/journal-entries/$entryId/reversal'
      path: '/reversal'
      fullPath: '/api/v1/journal-entries/$entryId/reversal'
      preLoaderRoute: typeof ApiV1JournalEntriesEntryIdReversalRouteImport
      parentRoute: typeof ApiV1JournalEntriesEntryIdRoute
    }
    '/api/v1/payment-batches/$batchId/instructions': {
      id: '/api/v1/payment-batches/$batchId/instructions'
      path: '/instructions'
      fullPath: '/api/v1/payment-batches/$batchId/instructions'
      preLoaderRoute: typeof ApiV1PaymentBatchesBatchIdInstructionsRouteImport
      parentRoute: typeof ApiV1PaymentBatchesBatchIdRoute
    }
    '/api/v1/payment-batches/$batchId/pain001': {
      id: '/api/v1/payment-batches/$batchId/pain001'
      path: '/pain001'
      fullPath: '/api/v1/payment-batches/$batchId/pain001'
      preLoaderRoute: typeof ApiV1PaymentBatchesBatchIdPain001RouteImport
      parentRoute: typeof ApiV1PaymentBatchesBatchIdRoute
    }
    '/api/v1/payment-batches/$batchId/transitions': {
      id: '/api/v1/payment-batches/$batchId/transitions'
      path: '/transitions'
      fullPath: '/api/v1/payment-batches/$batchId/transitions'
      preLoaderRoute: typeof ApiV1PaymentBatchesBatchIdTransitionsRouteImport
      parentRoute: typeof ApiV1PaymentBatchesBatchIdRoute
    }
    '/api/v1/sales-invoices/$invoiceId/deliveries': {
      id: '/api/v1/sales-invoices/$invoiceId/deliveries'
      path: '/deliveries'
      fullPath: '/api/v1/sales-invoices/$invoiceId/deliveries'
      preLoaderRoute: typeof ApiV1SalesInvoicesInvoiceIdDeliveriesRouteImport
      parentRoute: typeof ApiV1SalesInvoicesInvoiceIdRoute
    }
    '/api/v1/sales-invoices/$invoiceId/issue': {
      id: '/api/v1/sales-invoices/$invoiceId/issue'
      path: '/issue'
      fullPath: '/api/v1/sales-invoices/$invoiceId/issue'
      preLoaderRoute: typeof ApiV1SalesInvoicesInvoiceIdIssueRouteImport
      parentRoute: typeof ApiV1SalesInvoicesInvoiceIdRoute
    }
    '/api/v1/sales-invoices/$invoiceId/pdf': {
      id: '/api/v1/sales-invoices/$invoiceId/pdf'
      path: '/pdf'
      fullPath: '/api/v1/sales-invoices/$invoiceId/pdf'
      preLoaderRoute: typeof ApiV1SalesInvoicesInvoiceIdPdfRouteImport
      parentRoute: typeof ApiV1SalesInvoicesInvoiceIdRoute
    }
    '/api/v1/sales-invoices/$invoiceId/reminders': {
      id: '/api/v1/sales-invoices/$invoiceId/reminders'
      path: '/reminders'
      fullPath: '/api/v1/sales-invoices/$invoiceId/reminders'
      preLoaderRoute: typeof ApiV1SalesInvoicesInvoiceIdRemindersRouteImport
      parentRoute: typeof ApiV1SalesInvoicesInvoiceIdRoute
    }
    '/api/v1/sales-invoices/$invoiceId/send': {
      id: '/api/v1/sales-invoices/$invoiceId/send'
      path: '/send'
      fullPath: '/api/v1/sales-invoices/$invoiceId/send'
      preLoaderRoute: typeof ApiV1SalesInvoicesInvoiceIdSendRouteImport
      parentRoute: typeof ApiV1SalesInvoicesInvoiceIdRoute
    }
    '/api/v1/sales-invoices/$invoiceId/ubl': {
      id: '/api/v1/sales-invoices/$invoiceId/ubl'
      path: '/ubl'
      fullPath: '/api/v1/sales-invoices/$invoiceId/ubl'
      preLoaderRoute: typeof ApiV1SalesInvoicesInvoiceIdUblRouteImport
      parentRoute: typeof ApiV1SalesInvoicesInvoiceIdRoute
    }
    '/api/v1/vat/icp/$period': {
      id: '/api/v1/vat/icp/$period'
      path: '/api/v1/vat/icp/$period'
      fullPath: '/api/v1/vat/icp/$period'
      preLoaderRoute: typeof ApiV1VatIcpPeriodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/vat/returns/$period': {
      id: '/api/v1/vat/returns/$period'
      path: '/api/v1/vat/returns/$period'
      fullPath: '/api/v1/vat/returns/$period'
      preLoaderRoute: typeof ApiV1VatReturnsPeriodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/payment-batches/$batchId/instructions/$instructionId': {
      id: '/api/v1/payment-batches/$batchId/instructions/$instructionId'
      path: '/$instructionId'
      fullPath: '/api/v1/payment-batches/$batchId/instructions/$instructionId'
      preLoaderRoute: typeof ApiV1PaymentBatchesBatchIdInstructionsInstructionIdRouteImport
      parentRoute: typeof ApiV1PaymentBatchesBatchIdInstructionsRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppContactsRoute: typeof AppContactsRoute
  AppDunningRoute: typeof AppDunningRoute
  AppMembersRoute: typeof AppMembersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBankMatchRoute: typeof AppBankMatchRoute
  AppEntriesEntryIdRoute: typeof AppEntriesEntryIdRoute
  AppEntriesNewRoute: typeof AppEntriesNewRoute
  AppInvoicesInvoiceIdRoute: typeof AppInvoicesInvoiceIdRoute
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppPaymentsBatchIdRoute: typeof AppPaymentsBatchIdRoute
  AppReportsBalanceSheetRoute: typeof AppReportsBalanceSheetRoute
  AppReportsProfitAndLossRoute: typeof AppReportsProfitAndLossRoute
  AppReportsTrialBalanceRoute: typeof AppReportsTrialBalanceRoute
  AppVatPeriodRoute: typeof AppVatPeriodRoute
  AppBankIndexRoute: typeof AppBankIndexRoute
  AppEntriesIndexRoute: typeof AppEntriesIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppPaymentsIndexRoute: typeof AppPaymentsIndexRoute
  AppVatIndexRoute: typeof AppVatIndexRoute
  AppVatIcpPeriodRoute: typeof AppVatIcpPeriodRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppContactsRoute: AppContactsRoute,
  AppDunningRoute: AppDunningRoute,
  AppMembersRoute: AppMembersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBankMatchRoute: AppBankMatchRoute,
  AppEntriesEntryIdRoute: AppEntriesEntryIdRoute,
  AppEntriesNewRoute: AppEntriesNewRoute,
  AppInvoicesInvoiceIdRoute: AppInvoicesInvoiceIdRoute,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppPaymentsBatchIdRoute: AppPaymentsBatchIdRoute,
  AppReportsBalanceSheetRoute: AppReportsBalanceSheetRoute,
  AppReportsProfitAndLossRoute: AppReportsProfitAndLossRoute,
  AppReportsTrialBalanceRoute: AppReportsTrialBalanceRoute,
  AppVatPeriodRoute: AppVatPeriodRoute,
  AppBankIndexRoute: AppBankIndexRoute,
  AppEntriesIndexRoute: AppEntriesIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppPaymentsIndexRoute: AppPaymentsIndexRoute,
  AppVatIndexRoute: AppVatIndexRoute,
  AppVatIcpPeriodRoute: AppVatIcpPeriodRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiV1BankMatchRulesRouteChildren {
  ApiV1BankMatchRulesRuleIdRoute: typeof ApiV1BankMatchRulesRuleIdRoute
}

const ApiV1BankMatchRulesRouteChildren: ApiV1BankMatchRulesRouteChildren = {
  ApiV1BankMatchRulesRuleIdRoute: ApiV1BankMatchRulesRuleIdRoute,
}

const ApiV1BankMatchRulesRouteWithChildren =
  ApiV1BankMatchRulesRoute._addFileChildren(ApiV1BankMatchRulesRouteChildren)

interface ApiV1BankTransactionsRouteChildren {
  ApiV1BankTransactionsTransactionIdIgnoreRoute: typeof ApiV1BankTransactionsTransactionIdIgnoreRoute
  ApiV1BankTransactionsTransactionIdMatchRoute: typeof ApiV1BankTransactionsTransactionIdMatchRoute
  ApiV1BankTransactionsTransactionIdSuggestionsRoute: typeof ApiV1BankTransactionsTransactionIdSuggestionsRoute
}

const ApiV1BankTransactionsRouteChildren: ApiV1BankTransactionsRouteChildren = {
  ApiV1BankTransactionsTransactionIdIgnoreRoute:
    ApiV1BankTransactionsTransactionIdIgnoreRoute,
  ApiV1BankTransactionsTransactionIdMatchRoute:
    ApiV1BankTransactionsTransactionIdMatchRoute,
  ApiV1BankTransactionsTransactionIdSuggestionsRoute:
    ApiV1BankTransactionsTransactionIdSuggestionsRoute,
}

const ApiV1BankTransactionsRouteWithChildren =
  ApiV1BankTransactionsRoute._addFileChildren(
    ApiV1BankTransactionsRouteChildren,
  )

interface ApiV1FiscalYearsRouteChildren {
  ApiV1FiscalYearsCloseRoute: typeof ApiV1FiscalYearsCloseRoute
}

const ApiV1FiscalYearsRouteChildren: ApiV1FiscalYearsRouteChildren = {
  ApiV1FiscalYearsCloseRoute: ApiV1FiscalYearsCloseRoute,
}

const ApiV1FiscalYearsRouteWithChildren =
  ApiV1FiscalYearsRoute._addFileChildren(ApiV1FiscalYearsRouteChildren)

interface ApiV1JournalEntriesEntryIdRouteChildren {
  ApiV1JournalEntriesEntryIdReversalRoute: typeof ApiV1JournalEntriesEntryIdReversalRoute
}

const ApiV1JournalEntriesEntryIdRouteChildren: ApiV1JournalEntriesEntryIdRouteChildren =
  {
    ApiV1JournalEntriesEntryIdReversalRoute:
      ApiV1JournalEntriesEntryIdReversalRoute,
  }

const ApiV1JournalEntriesEntryIdRouteWithChildren =
  ApiV1JournalEntriesEntryIdRoute._addFileChildren(
    ApiV1JournalEntriesEntryIdRouteChildren,
  )

interface ApiV1JournalEntriesRouteChildren {
  ApiV1JournalEntriesEntryIdRoute: typeof ApiV1JournalEntriesEntryIdRouteWithChildren
}

const ApiV1JournalEntriesRouteChildren: ApiV1JournalEntriesRouteChildren = {
  ApiV1JournalEntriesEntryIdRoute: ApiV1JournalEntriesEntryIdRouteWithChildren,
}

const ApiV1JournalEntriesRouteWithChildren =
  ApiV1JournalEntriesRoute._addFileChildren(ApiV1JournalEntriesRouteChildren)

interface ApiV1MembersRouteChildren {
  ApiV1MembersMemberIdRoute: typeof ApiV1MembersMemberIdRoute
}

const ApiV1MembersRouteChildren: ApiV1MembersRouteChildren = {
  ApiV1MembersMemberIdRoute: ApiV1MembersMemberIdRoute,
}

const ApiV1MembersRouteWithChildren = ApiV1MembersRoute._addFileChildren(
  ApiV1MembersRouteChildren,
)

interface ApiV1PaymentBatchesBatchIdInstructionsRouteChildren {
  ApiV1PaymentBatchesBatchIdInstructionsInstructionIdRoute: typeof ApiV1PaymentBatchesBatchIdInstructionsInstructionIdRoute
}

const ApiV1PaymentBatchesBatchIdInstructionsRouteChildren: ApiV1PaymentBatchesBatchIdInstructionsRouteChildren =
  {
    ApiV1PaymentBatchesBatchIdInstructionsInstructionIdRoute:
      ApiV1PaymentBatchesBatchIdInstructionsInstructionIdRoute,
  }

const ApiV1PaymentBatchesBatchIdInstructionsRouteWithChildren =
  ApiV1PaymentBatchesBatchIdInstructionsRoute._addFileChildren(
    ApiV1PaymentBatchesBatchIdInstructionsRouteChildren,
  )

interface ApiV1PaymentBatchesBatchIdRouteChildren {
  ApiV1PaymentBatchesBatchIdInstructionsRoute: typeof ApiV1PaymentBatchesBatchIdInstructionsRouteWithChildren
  ApiV1PaymentBatchesBatchIdPain001Route: typeof ApiV1PaymentBatchesBatchIdPain001Route
  ApiV1PaymentBatchesBatchIdTransitionsRoute: typeof ApiV1PaymentBatchesBatchIdTransitionsRoute
}

const ApiV1PaymentBatchesBatchIdRouteChildren: ApiV1PaymentBatchesBatchIdRouteChildren =
  {
    ApiV1PaymentBatchesBatchIdInstructionsRoute:
      ApiV1PaymentBatchesBatchIdInstructionsRouteWithChildren,
    ApiV1PaymentBatchesBatchIdPain001Route:
      ApiV1PaymentBatchesBatchIdPain001Route,
    ApiV1PaymentBatchesBatchIdTransitionsRoute:
      ApiV1PaymentBatchesBatchIdTransitionsRoute,
  }

const ApiV1PaymentBatchesBatchIdRouteWithChildren =
  ApiV1PaymentBatchesBatchIdRoute._addFileChildren(
    ApiV1PaymentBatchesBatchIdRouteChildren,
  )

interface ApiV1PaymentBatchesRouteChildren {
  ApiV1PaymentBatchesBatchIdRoute: typeof ApiV1PaymentBatchesBatchIdRouteWithChildren
}

const ApiV1PaymentBatchesRouteChildren: ApiV1PaymentBatchesRouteChildren = {
  ApiV1PaymentBatchesBatchIdRoute: ApiV1PaymentBatchesBatchIdRouteWithChildren,
}

const ApiV1PaymentBatchesRouteWithChildren =
  ApiV1PaymentBatchesRoute._addFileChildren(ApiV1PaymentBatchesRouteChildren)

interface ApiV1SalesInvoicesInvoiceIdRouteChildren {
  ApiV1SalesInvoicesInvoiceIdDeliveriesRoute: typeof ApiV1SalesInvoicesInvoiceIdDeliveriesRoute
  ApiV1SalesInvoicesInvoiceIdIssueRoute: typeof ApiV1SalesInvoicesInvoiceIdIssueRoute
  ApiV1SalesInvoicesInvoiceIdPdfRoute: typeof ApiV1SalesInvoicesInvoiceIdPdfRoute
  ApiV1SalesInvoicesInvoiceIdRemindersRoute: typeof ApiV1SalesInvoicesInvoiceIdRemindersRoute
  ApiV1SalesInvoicesInvoiceIdSendRoute: typeof ApiV1SalesInvoicesInvoiceIdSendRoute
  ApiV1SalesInvoicesInvoiceIdUblRoute: typeof ApiV1SalesInvoicesInvoiceIdUblRoute
}

const ApiV1SalesInvoicesInvoiceIdRouteChildren: ApiV1SalesInvoicesInvoiceIdRouteChildren =
  {
    ApiV1SalesInvoicesInvoiceIdDeliveriesRoute:
      ApiV1SalesInvoicesInvoiceIdDeliveriesRoute,
    ApiV1SalesInvoicesInvoiceIdIssueRoute:
      ApiV1SalesInvoicesInvoiceIdIssueRoute,
    ApiV1SalesInvoicesInvoiceIdPdfRoute: ApiV1SalesInvoicesInvoiceIdPdfRoute,
    ApiV1SalesInvoicesInvoiceIdRemindersRoute:
      ApiV1SalesInvoicesInvoiceIdRemindersRoute,
    ApiV1SalesInvoicesInvoiceIdSendRoute: ApiV1SalesInvoicesInvoiceIdSendRoute,
    ApiV1SalesInvoicesInvoiceIdUblRoute: ApiV1SalesInvoicesInvoiceIdUblRoute,
  }

const ApiV1SalesInvoicesInvoiceIdRouteWithChildren =
  ApiV1SalesInvoicesInvoiceIdRoute._addFileChildren(
    ApiV1SalesInvoicesInvoiceIdRouteChildren,
  )

interface ApiV1SalesInvoicesRouteChildren {
  ApiV1SalesInvoicesInvoiceIdRoute: typeof ApiV1SalesInvoicesInvoiceIdRouteWithChildren
}

const ApiV1SalesInvoicesRouteChildren: ApiV1SalesInvoicesRouteChildren = {
  ApiV1SalesInvoicesInvoiceIdRoute:
    ApiV1SalesInvoicesInvoiceIdRouteWithChildren,
}

const ApiV1SalesInvoicesRouteWithChildren =
  ApiV1SalesInvoicesRoute._addFileChildren(ApiV1SalesInvoicesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SetupRoute: SetupRoute,
  SignInRoute: SignInRoute,
  SignOutRoute: SignOutRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1AccountsRoute: ApiV1AccountsRoute,
  ApiV1BankAccountsRoute: ApiV1BankAccountsRoute,
  ApiV1BankMatchRulesRoute: ApiV1BankMatchRulesRouteWithChildren,
  ApiV1BankStatementsRoute: ApiV1BankStatementsRoute,
  ApiV1BankTransactionsRoute: ApiV1BankTransactionsRouteWithChildren,
  ApiV1ContactsRoute: ApiV1ContactsRoute,
  ApiV1EntityRoute: ApiV1EntityRoute,
  ApiV1FiscalYearsRoute: ApiV1FiscalYearsRouteWithChildren,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1JournalEntriesRoute: ApiV1JournalEntriesRouteWithChildren,
  ApiV1MembersRoute: ApiV1MembersRouteWithChildren,
  ApiV1PaymentBatchesRoute: ApiV1PaymentBatchesRouteWithChildren,
  ApiV1SalesInvoicesRoute: ApiV1SalesInvoicesRouteWithChildren,
  ApiV1TaxCodesRoute: ApiV1TaxCodesRoute,
  ApiV1EntitiesEntityIdRoute: ApiV1EntitiesEntityIdRoute,
  ApiV1ExportsAuditFileRoute: ApiV1ExportsAuditFileRoute,
  ApiV1ImportsAuditFileRoute: ApiV1ImportsAuditFileRoute,
  ApiV1LedgerChainVerificationRoute: ApiV1LedgerChainVerificationRoute,
  ApiV1ReportsBalanceSheetRoute: ApiV1ReportsBalanceSheetRoute,
  ApiV1ReportsDunningRoute: ApiV1ReportsDunningRoute,
  ApiV1ReportsOverdueInvoicesRoute: ApiV1ReportsOverdueInvoicesRoute,
  ApiV1ReportsProfitAndLossRoute: ApiV1ReportsProfitAndLossRoute,
  ApiV1ReportsTrialBalanceRoute: ApiV1ReportsTrialBalanceRoute,
  ApiV1RgsCoverageRoute: ApiV1RgsCoverageRoute,
  ApiV1RgsMappingsRoute: ApiV1RgsMappingsRoute,
  ApiV1RgsUpgradePreviewRoute: ApiV1RgsUpgradePreviewRoute,
  ApiV1SetupChartsRoute: ApiV1SetupChartsRoute,
  ApiV1VatFilingsRoute: ApiV1VatFilingsRoute,
  ApiV1VatNumberChecksRoute: ApiV1VatNumberChecksRoute,
  ApiV1VatPeriodsRoute: ApiV1VatPeriodsRoute,
  ApiV1VatIcpPeriodRoute: ApiV1VatIcpPeriodRoute,
  ApiV1VatReturnsPeriodRoute: ApiV1VatReturnsPeriodRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
