/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiV1AccountsRouteImport } from './routes/api/v1/accounts'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1JournalEntriesRouteImport } from './routes/api/v1/journal-entries'
import { Route as ApiV1ExportsAuditFileRouteImport } from './routes/api/v1/exports.audit-file'
import { Route as ApiV1FiscalYearsCloseRouteImport } from './routes/api/v1/fiscal-years.close'
import { Route as ApiV1ImportsAuditFileRouteImport } from './routes/api/v1/imports.audit-file'
import { Route as ApiV1JournalEntriesEntryIdRouteImport } from './routes/api/v1/journal-entries.$entryId'
import { Route as ApiV1LedgerChainVerificationRouteImport } from './routes/api/v1/ledger.chain-verification'
import { Route as ApiV1ReportsBalanceSheetRouteImport } from './routes/api/v1/reports.balance-sheet'
import { Route as ApiV1ReportsProfitAndLossRouteImport } from './routes/api/v1/reports.profit-and-loss'
import { Route as ApiV1ReportsTrialBalanceRouteImport } from './routes/api/v1/reports.trial-balance'
import { Route as ApiV1RgsCoverageRouteImport } from './routes/api/v1/rgs.coverage'
import { Route as ApiV1RgsMappingsRouteImport } from './routes/api/v1/rgs.mappings'
import { Route as ApiV1RgsUpgradePreviewRouteImport } from './routes/api/v1/rgs.upgrade-preview'
import { Route as ApiV1JournalEntriesEntryIdReversalRouteImport } from './routes/api/v1/journal-entries.$entryId.reversal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AccountsRoute = ApiV1AccountsRouteImport.update({
  id: '/api/v1/accounts',
  path: '/api/v1/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JournalEntriesRoute = ApiV1JournalEntriesRouteImport.update({
  id: '/api/v1/journal-entries',
  path: '/api/v1/journal-entries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ExportsAuditFileRoute = ApiV1ExportsAuditFileRouteImport.update({
  id: '/api/v1/exports/audit-file',
  path: '/api/v1/exports/audit-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FiscalYearsCloseRoute = ApiV1FiscalYearsCloseRouteImport.update({
  id: '/api/v1/fiscal-years/close',
  path: '/api/v1/fiscal-years/close',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ImportsAuditFileRoute = ApiV1ImportsAuditFileRouteImport.update({
  id: '/api/v1/imports/audit-file',
  path: '/api/v1/imports/audit-file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JournalEntriesEntryIdRoute =
  ApiV1JournalEntriesEntryIdRouteImport.update({
    id: '/$entryId',
    path: '/$entryId',
    getParentRoute: () => ApiV1JournalEntriesRoute,
  } as any)
const ApiV1LedgerChainVerificationRoute =
  ApiV1LedgerChainVerificationRouteImport.update({
    id: '/api/v1/ledger/chain-verification',
    path: '/api/v1/ledger/chain-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ReportsBalanceSheetRoute =
  ApiV1ReportsBalanceSheetRouteImport.update({
    id: '/api/v1/reports/balance-sheet',
    path: '/api/v1/reports/balance-sheet',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ReportsProfitAndLossRoute =
  ApiV1ReportsProfitAndLossRouteImport.update({
    id: '/api/v1/reports/profit-and-loss',
    path: '/api/v1/reports/profit-and-loss',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ReportsTrialBalanceRoute =
  ApiV1ReportsTrialBalanceRouteImport.update({
    id: '/api/v1/reports/trial-balance',
    path: '/api/v1/reports/trial-balance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1RgsCoverageRoute = ApiV1RgsCoverageRouteImport.update({
  id: '/api/v1/rgs/coverage',
  path: '/api/v1/rgs/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RgsMappingsRoute = ApiV1RgsMappingsRouteImport.update({
  id: '/api/v1/rgs/mappings',
  path: '/api/v1/rgs/mappings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RgsUpgradePreviewRoute = ApiV1RgsUpgradePreviewRouteImport.update({
  id: '/api/v1/rgs/upgrade-preview',
  path: '/api/v1/rgs/upgrade-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JournalEntriesEntryIdReversalRoute =
  ApiV1JournalEntriesEntryIdReversalRouteImport.update({
    id: '/reversal',
    path: '/reversal',
    getParentRoute: () => ApiV1JournalEntriesEntryIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/v1/accounts': typeof ApiV1AccountsRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/journal-entries': typeof ApiV1JournalEntriesRouteWithChildren
  '/api/v1/exports/audit-file': typeof ApiV1ExportsAuditFileRoute
  '/api/v1/fiscal-years/close': typeof ApiV1FiscalYearsCloseRoute
  '/api/v1/imports/audit-file': typeof ApiV1ImportsAuditFileRoute
  '/api/v1/journal-entries/$entryId': typeof ApiV1JournalEntriesEntryIdRouteWithChildren
  '/api/v1/ledger/chain-verification': typeof ApiV1LedgerChainVerificationRoute
  '/api/v1/reports/balance-sheet': typeof ApiV1ReportsBalanceSheetRoute
  '/api/v1/reports/profit-and-loss': typeof ApiV1ReportsProfitAndLossRoute
  '/api/v1/reports/trial-balance': typeof ApiV1ReportsTrialBalanceRoute
  '/api/v1/rgs/coverage': typeof ApiV1RgsCoverageRoute
  '/api/v1/rgs/mappings': typeof ApiV1RgsMappingsRoute
  '/api/v1/rgs/upgrade-preview': typeof ApiV1RgsUpgradePreviewRoute
  '/api/v1/journal-entries/$entryId/reversal': typeof ApiV1JournalEntriesEntryIdReversalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/v1/accounts': typeof ApiV1AccountsRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/journal-entries': typeof ApiV1JournalEntriesRouteWithChildren
  '/api/v1/exports/audit-file': typeof ApiV1ExportsAuditFileRoute
  '/api/v1/fiscal-years/close': typeof ApiV1FiscalYearsCloseRoute
  '/api/v1/imports/audit-file': typeof ApiV1ImportsAuditFileRoute
  '/api/v1/journal-entries/$entryId': typeof ApiV1JournalEntriesEntryIdRouteWithChildren
  '/api/v1/ledger/chain-verification': typeof ApiV1LedgerChainVerificationRoute
  '/api/v1/reports/balance-sheet': typeof ApiV1ReportsBalanceSheetRoute
  '/api/v1/reports/profit-and-loss': typeof ApiV1ReportsProfitAndLossRoute
  '/api/v1/reports/trial-balance': typeof ApiV1ReportsTrialBalanceRoute
  '/api/v1/rgs/coverage': typeof ApiV1RgsCoverageRoute
  '/api/v1/rgs/mappings': typeof ApiV1RgsMappingsRoute
  '/api/v1/rgs/upgrade-preview': typeof ApiV1RgsUpgradePreviewRoute
  '/api/v1/journal-entries/$entryId/reversal': typeof ApiV1JournalEntriesEntryIdReversalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/v1/accounts': typeof ApiV1AccountsRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/journal-entries': typeof ApiV1JournalEntriesRouteWithChildren
  '/api/v1/exports/audit-file': typeof ApiV1ExportsAuditFileRoute
  '/api/v1/fiscal-years/close': typeof ApiV1FiscalYearsCloseRoute
  '/api/v1/imports/audit-file': typeof ApiV1ImportsAuditFileRoute
  '/api/v1/journal-entries/$entryId': typeof ApiV1JournalEntriesEntryIdRouteWithChildren
  '/api/v1/ledger/chain-verification': typeof ApiV1LedgerChainVerificationRoute
  '/api/v1/reports/balance-sheet': typeof ApiV1ReportsBalanceSheetRoute
  '/api/v1/reports/profit-and-loss': typeof ApiV1ReportsProfitAndLossRoute
  '/api/v1/reports/trial-balance': typeof ApiV1ReportsTrialBalanceRoute
  '/api/v1/rgs/coverage': typeof ApiV1RgsCoverageRoute
  '/api/v1/rgs/mappings': typeof ApiV1RgsMappingsRoute
  '/api/v1/rgs/upgrade-preview': typeof ApiV1RgsUpgradePreviewRoute
  '/api/v1/journal-entries/$entryId/reversal': typeof ApiV1JournalEntriesEntryIdReversalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/v1/accounts'
    | '/api/v1/health'
    | '/api/v1/journal-entries'
    | '/api/v1/exports/audit-file'
    | '/api/v1/fiscal-years/close'
    | '/api/v1/imports/audit-file'
    | '/api/v1/journal-entries/$entryId'
    | '/api/v1/ledger/chain-verification'
    | '/api/v1/reports/balance-sheet'
    | '/api/v1/reports/profit-and-loss'
    | '/api/v1/reports/trial-balance'
    | '/api/v1/rgs/coverage'
    | '/api/v1/rgs/mappings'
    | '/api/v1/rgs/upgrade-preview'
    | '/api/v1/journal-entries/$entryId/reversal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/v1/accounts'
    | '/api/v1/health'
    | '/api/v1/journal-entries'
    | '/api/v1/exports/audit-file'
    | '/api/v1/fiscal-years/close'
    | '/api/v1/imports/audit-file'
    | '/api/v1/journal-entries/$entryId'
    | '/api/v1/ledger/chain-verification'
    | '/api/v1/reports/balance-sheet'
    | '/api/v1/reports/profit-and-loss'
    | '/api/v1/reports/trial-balance'
    | '/api/v1/rgs/coverage'
    | '/api/v1/rgs/mappings'
    | '/api/v1/rgs/upgrade-preview'
    | '/api/v1/journal-entries/$entryId/reversal'
  id:
    | '__root__'
    | '/'
    | '/api/v1/accounts'
    | '/api/v1/health'
    | '/api/v1/journal-entries'
    | '/api/v1/exports/audit-file'
    | '/api/v1/fiscal-years/close'
    | '/api/v1/imports/audit-file'
    | '/api/v1/journal-entries/$entryId'
    | '/api/v1/ledger/chain-verification'
    | '/api/v1/reports/balance-sheet'
    | '/api/v1/reports/profit-and-loss'
    | '/api/v1/reports/trial-balance'
    | '/api/v1/rgs/coverage'
    | '/api/v1/rgs/mappings'
    | '/api/v1/rgs/upgrade-preview'
    | '/api/v1/journal-entries/$entryId/reversal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiV1AccountsRoute: typeof ApiV1AccountsRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1JournalEntriesRoute: typeof ApiV1JournalEntriesRouteWithChildren
  ApiV1ExportsAuditFileRoute: typeof ApiV1ExportsAuditFileRoute
  ApiV1FiscalYearsCloseRoute: typeof ApiV1FiscalYearsCloseRoute
  ApiV1ImportsAuditFileRoute: typeof ApiV1ImportsAuditFileRoute
  ApiV1LedgerChainVerificationRoute: typeof ApiV1LedgerChainVerificationRoute
  ApiV1ReportsBalanceSheetRoute: typeof ApiV1ReportsBalanceSheetRoute
  ApiV1ReportsProfitAndLossRoute: typeof ApiV1ReportsProfitAndLossRoute
  ApiV1ReportsTrialBalanceRoute: typeof ApiV1ReportsTrialBalanceRoute
  ApiV1RgsCoverageRoute: typeof ApiV1RgsCoverageRoute
  ApiV1RgsMappingsRoute: typeof ApiV1RgsMappingsRoute
  ApiV1RgsUpgradePreviewRoute: typeof ApiV1RgsUpgradePreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/accounts': {
      id: '/api/v1/accounts'
      path: '/api/v1/accounts'
      fullPath: '/api/v1/accounts'
      preLoaderRoute: typeof ApiV1AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/journal-entries': {
      id: '/api/v1/journal-entries'
      path: '/api/v1/journal-entries'
      fullPath: '/api/v1/journal-entries'
      preLoaderRoute: typeof ApiV1JournalEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/exports/audit-file': {
      id: '/api/v1/exports/audit-file'
      path: '/api/v1/exports/audit-file'
      fullPath: '/api/v1/exports/audit-file'
      preLoaderRoute: typeof ApiV1ExportsAuditFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/fiscal-years/close': {
      id: '/api/v1/fiscal-years/close'
      path: '/api/v1/fiscal-years/close'
      fullPath: '/api/v1/fiscal-years/close'
      preLoaderRoute: typeof ApiV1FiscalYearsCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/imports/audit-file': {
      id: '/api/v1/imports/audit-file'
      path: '/api/v1/imports/audit-file'
      fullPath: '/api/v1/imports/audit-file'
      preLoaderRoute: typeof ApiV1ImportsAuditFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/journal-entries/$entryId': {
      id: '/api/v1/journal-entries/$entryId'
      path: '/$entryId'
      fullPath: '/api/v1/journal-entries/$entryId'
      preLoaderRoute: typeof ApiV1JournalEntriesEntryIdRouteImport
      parentRoute: typeof ApiV1JournalEntriesRoute
    }
    '/api/v1/ledger/chain-verification': {
      id: '/api/v1/ledger/chain-verification'
      path: '/api/v1/ledger/chain-verification'
      fullPath: '/api/v1/ledger/chain-verification'
      preLoaderRoute: typeof ApiV1LedgerChainVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports/balance-sheet': {
      id: '/api/v1/reports/balance-sheet'
      path: '/api/v1/reports/balance-sheet'
      fullPath: '/api/v1/reports/balance-sheet'
      preLoaderRoute: typeof ApiV1ReportsBalanceSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports/profit-and-loss': {
      id: '/api/v1/reports/profit-and-loss'
      path: '/api/v1/reports/profit-and-loss'
      fullPath: '/api/v1/reports/profit-and-loss'
      preLoaderRoute: typeof ApiV1ReportsProfitAndLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/reports/trial-balance': {
      id: '/api/v1/reports/trial-balance'
      path: '/api/v1/reports/trial-balance'
      fullPath: '/api/v1/reports/trial-balance'
      preLoaderRoute: typeof ApiV1ReportsTrialBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/rgs/coverage': {
      id: '/api/v1/rgs/coverage'
      path: '/api/v1/rgs/coverage'
      fullPath: '/api/v1/rgs/coverage'
      preLoaderRoute: typeof ApiV1RgsCoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/rgs/mappings': {
      id: '/api/v1/rgs/mappings'
      path: '/api/v1/rgs/mappings'
      fullPath: '/api/v1/rgs/mappings'
      preLoaderRoute: typeof ApiV1RgsMappingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/rgs/upgrade-preview': {
      id: '/api/v1/rgs/upgrade-preview'
      path: '/api/v1/rgs/upgrade-preview'
      fullPath: '/api/v1/rgs/upgrade-preview'
      preLoaderRoute: typeof ApiV1RgsUpgradePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/journal-entries/$entryId/reversal': {
      id: '/api/v1/journal-entries/$entryId/reversal'
      path: '/reversal'
      fullPath: '/api/v1/journal-entries/$entryId/reversal'
      preLoaderRoute: typeof ApiV1JournalEntriesEntryIdReversalRouteImport
      parentRoute: typeof ApiV1JournalEntriesEntryIdRoute
    }
  }
}

interface ApiV1JournalEntriesEntryIdRouteChildren {
  ApiV1JournalEntriesEntryIdReversalRoute: typeof ApiV1JournalEntriesEntryIdReversalRoute
}

const ApiV1JournalEntriesEntryIdRouteChildren: ApiV1JournalEntriesEntryIdRouteChildren =
  {
    ApiV1JournalEntriesEntryIdReversalRoute:
      ApiV1JournalEntriesEntryIdReversalRoute,
  }

const ApiV1JournalEntriesEntryIdRouteWithChildren =
  ApiV1JournalEntriesEntryIdRoute._addFileChildren(
    ApiV1JournalEntriesEntryIdRouteChildren,
  )

interface ApiV1JournalEntriesRouteChildren {
  ApiV1JournalEntriesEntryIdRoute: typeof ApiV1JournalEntriesEntryIdRouteWithChildren
}

const ApiV1JournalEntriesRouteChildren: ApiV1JournalEntriesRouteChildren = {
  ApiV1JournalEntriesEntryIdRoute: ApiV1JournalEntriesEntryIdRouteWithChildren,
}

const ApiV1JournalEntriesRouteWithChildren =
  ApiV1JournalEntriesRoute._addFileChildren(ApiV1JournalEntriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiV1AccountsRoute: ApiV1AccountsRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1JournalEntriesRoute: ApiV1JournalEntriesRouteWithChildren,
  ApiV1ExportsAuditFileRoute: ApiV1ExportsAuditFileRoute,
  ApiV1FiscalYearsCloseRoute: ApiV1FiscalYearsCloseRoute,
  ApiV1ImportsAuditFileRoute: ApiV1ImportsAuditFileRoute,
  ApiV1LedgerChainVerificationRoute: ApiV1LedgerChainVerificationRoute,
  ApiV1ReportsBalanceSheetRoute: ApiV1ReportsBalanceSheetRoute,
  ApiV1ReportsProfitAndLossRoute: ApiV1ReportsProfitAndLossRoute,
  ApiV1ReportsTrialBalanceRoute: ApiV1ReportsTrialBalanceRoute,
  ApiV1RgsCoverageRoute: ApiV1RgsCoverageRoute,
  ApiV1RgsMappingsRoute: ApiV1RgsMappingsRoute,
  ApiV1RgsUpgradePreviewRoute: ApiV1RgsUpgradePreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
