import type { AccountType } from '../ledger/types.js'
import type { ExactDivision } from '../ports/exact.js'
import {
  classifyAccount,
  rolesFor,
  type ExactAccount,
  type ExactAttachment,
  type ExactDocument,
  type ExactGLAccount,
  type ExactOpenItem,
  type ExactPaymentCondition,
  type ExactReportingBalance,
  type ExactVatCode,
} from './resources.js'

/**
 * What importing an Exact division would do, before it does it (spec 13).
 *
 * "A dry-run mode producing a reconciliation report against the source
 * system's trial balance before anything is committed."
 *
 * That sentence is the whole design of this module. The plan is a pure function
 * of what was read from Exact and what already exists here — no database, no
 * clock, no network — so the report a human approves is exactly the thing that
 * gets executed, rather than a preview generated by a second code path that
 * might disagree with the first.
 *
 * ## What is reconciled, and why it is these three things
 *
 * The Exact importer brings master data and open items across, not history —
 * history is what the XAF import is for. So there is no set of postings to
 * compare against a trial balance line by line. What there is, and what an
 * accountant would actually ask for, is three questions:
 *
 * 1. **Does Exact's own trial balance balance?** If debit and credit do not
 *    agree in the source, nothing downstream of it can be trusted, and finding
 *    that out after the import is finding it out too late.
 * 2. **Do the open items add up to the control accounts?** Exact's receivables
 *    list should total to what its debtors account holds, and the payables list
 *    to its creditors account. When they agree, the open items we are about to
 *    import are provably the complete debtor and creditor position. When they
 *    do not, something in Exact is booked to the control account without an
 *    open item behind it, and importing the list would start us short.
 * 3. **Is every account the trial balance mentions in the chart we are
 *    importing?** A code with a balance and no account is a line that would
 *    have nowhere to land.
 *
 * The first is a `problem`. The other two are reported as differences with
 * their amounts, because a real migration often has a known and explicable one
 * — and refusing to proceed on a two-cent rounding difference in a
 * twelve-year-old administration would make the tool useless. What it must not
 * do is fail to mention it.
 */

/** Something wrong with what Exact returned, or with what it would mean here. */
export type ExactProblemCode =
  | 'trial_balance_unbalanced'
  | 'trial_balance_account_missing'
  | 'open_items_do_not_reconcile'
  | 'no_control_account'
  | 'account_number_collision'
  | 'contact_number_collision'
  | 'unknown_currency'
  | 'derived_account_type'
  | 'unknown_tax_code'
  | 'payment_term_not_representable'
  | 'attachment_without_url'
  | 'division_caution'
  | 'resource_unreadable'
  | 'trial_balance_empty'

export interface ExactProblem {
  readonly code: ExactProblemCode
  readonly path: string | null
  readonly message: string
}

function problem(code: ExactProblemCode, path: string | null, message: string): ExactProblem {
  return { code, path, message }
}

/**
 * What to actually do about a 403, given what Exact was willing to say.
 *
 * Three different sentences, because they send somebody to three different
 * places. Telling a user to check their rights when the rights are fine and
 * the subscription is the problem wastes an afternoon.
 */
function diagnose(missing: UnreadableResource): string {
  if (missing.userHasRight === false) {
    return ` Exact confirms this user does not have GET rights on ${missing.resource} in this administration: check the roles on that user under Stamgegevens → Gebruikers, or connect as somebody who has them.`
  }
  if (missing.userHasRight === true) {
    return ` Exact says this user *does* have GET rights on ${missing.resource}, so the refusal is not their role — it is the administration's subscription not including the module, or the app registration's own data scoping.`
  }
  return ` Exact grants rights per resource rather than per scope, and would not answer whether this user has this one. It is one of four things: the user's roles on this administration, the subscription's modules, the administration itself, or the app registration's data scoping.`
}

// ---------------------------------------------------------------------------
// What was read
// ---------------------------------------------------------------------------

/**
 * Everything one division-scoped read pass collected.
 *
 * A snapshot rather than a client, so that planning is testable from a fixture
 * and a plan can be shown, stored and re-shown without asking Exact again.
 */
export interface ExactSnapshot {
  readonly division: ExactDivision
  readonly glAccounts: readonly ExactGLAccount[]
  readonly vatCodes: readonly ExactVatCode[]
  readonly accounts: readonly ExactAccount[]
  readonly paymentConditions: readonly ExactPaymentCondition[]
  readonly receivables: readonly ExactOpenItem[]
  readonly payables: readonly ExactOpenItem[]
  /**
   * `financial/ReportingBalance` for one year, both statuses.
   *
   * `null` when it could not be read, which is not the same as empty and must
   * not be allowed to look like it. An empty trial balance has debit equal to
   * credit, so it balances; treating an unread one as empty would report a
   * division as reconciled without having looked, and would report every open
   * item as a difference against a control account of zero.
   */
  readonly trialBalance: readonly ExactReportingBalance[] | null
  readonly year: number
  readonly documents: readonly ExactDocument[]
  readonly attachments: readonly ExactAttachment[]
  /** Resources the read pass was refused. Empty on a division that read cleanly. */
  readonly unreadable: readonly UnreadableResource[]
}

/**
 * A resource the read pass asked for and did not get.
 *
 * Exact's rights are per resource, not per scope: `vat/VATCodes` and
 * `financial/ReportingBalance` are both "Financial accounting", and a login can
 * be allowed the first and refused the second. So a division that reads fine
 * for six resources can answer 403 for the seventh, and that has to be a fact
 * the report carries rather than an exception that ends it.
 */
export interface UnreadableResource {
  /** The path asked for, e.g. `financial/ReportingBalance`. */
  readonly resource: string
  /** Exact's status. 403 is rights; 404 is a resource this division has not got. */
  readonly status: number
  readonly message: string
  /**
   * What `users/UserHasRights` said about this endpoint, if it was asked.
   *
   * A 403 from Exact has at least four causes and the error body distinguishes
   * none of them: the signed-in user's rights, the subscription's modules, the
   * division, and the app's own data scoping. This is the one of those Exact
   * will answer directly, so the report can say *which* thing to go and change
   * rather than listing the possibilities.
   *
   * `null` means the probe was not asked or could not be answered — it is
   * scoped `Organization administration`, and a login refused the resource can
   * be refused the question too. Not knowing is not a "no".
   */
  readonly userHasRight?: boolean | null
}

/** What this administration already has, so the plan can say new or existing. */
export interface ExactImportOptions {
  readonly entityId: string
  /** The entity's own currency. A division in another one is a problem. */
  readonly currency: string
  readonly existingAccountNumbers: readonly string[]
  readonly existingContactNumbers: readonly string[]
  readonly existingTaxCodes: readonly string[]
  /**
   * Exact's account types for the debtors and creditors control accounts: 20
   * and 22. Overridable because a division can have more than one of each, and
   * because a chart that was migrated into Exact from somewhere else sometimes
   * has them typed as `90 = General`.
   */
  readonly receivableAccountCodes?: readonly string[]
  readonly payableAccountCodes?: readonly string[]
}

// ---------------------------------------------------------------------------
// What the plan says
// ---------------------------------------------------------------------------

export interface ExactPlannedAccount {
  readonly number: string
  readonly name: string
  readonly type: AccountType
  readonly normalBalance: 'debit' | 'credit'
  readonly isBlocked: boolean
  readonly defaultTaxCode: string | null
  /** Exact's `ReportingCode`, which is sometimes an RGS code and sometimes not. */
  readonly reportingCode: string | null
  /** True when this number already exists here and would be left alone. */
  readonly exists: boolean
  /** True when the type came from `BalanceType`/`BalanceSide` rather than `Type`. */
  readonly derived: boolean
  readonly exactType: number | null
  readonly exactTypeDescription: string | null
}

export interface ExactPlannedContact {
  readonly number: string
  readonly name: string
  readonly isCustomer: boolean
  readonly isSupplier: boolean
  readonly vatNumber: string | null
  readonly kvkNumber: string | null
  readonly countryCode: string
  readonly email: string | null
  readonly phone: string | null
  readonly paymentTermsDays: number
  readonly isBlocked: boolean
  readonly address: {
    readonly line1: string | null
    readonly line2: string | null
    readonly postcode: string | null
    readonly city: string | null
    readonly countryCode: string
  } | null
  readonly exists: boolean
  /** Exact's GUID, kept so a re-import matches rather than duplicating. */
  readonly externalId: string
}

export interface ExactPlannedOpenItem {
  readonly side: 'receivable' | 'payable'
  readonly contactNumber: string
  readonly contactName: string
  /** The number the invoice carries in Exact, preserved. */
  readonly documentNumber: string
  readonly issuedOn: string
  readonly dueOn: string
  readonly outstanding: bigint
  readonly currency: string
  readonly description: string | null
  readonly theirReference: string | null
  readonly externalId: string
}

export interface ExactPlannedDocument {
  readonly externalId: string
  readonly subject: string
  readonly documentDate: string | null
  readonly contactNumber: string | null
  readonly typeDescription: string | null
  readonly attachments: readonly {
    readonly externalId: string
    readonly fileName: string
    readonly fileSize: number
    readonly url: string
  }[]
}

export interface ExactPlannedTaxCode {
  readonly code: string
  readonly description: string
  /** As a percentage, not Exact's fraction: 21 rather than 0.21. */
  readonly percentage: string
  readonly appliesTo: 'both' | 'purchase' | 'sales' | 'unknown'
  readonly reverseCharge: boolean
  /** True when a code of this name already exists here. */
  readonly mapped: boolean
}

/**
 * One side of the open-items reconciliation.
 *
 * `outcome` rather than a boolean, because there are four answers and only one
 * of them is "no". "The control account and the open items disagree" is a
 * finding about the administration; "there was no trial balance to compare
 * against" is a finding about our access to it. A boolean would report the
 * second as the first, which is a diagnosis of somebody else's books that we
 * have not earned.
 */
export type ControlAccountOutcome = 'matches' | 'differs' | 'no_control_account' | 'not_reconciled'

export interface ControlAccountCheck {
  readonly side: 'receivable' | 'payable'
  /** The account codes in Exact this side was measured against. */
  readonly accountCodes: readonly string[]
  /**
   * What the trial balance says those accounts hold, as a positive amount.
   * Null when the trial balance could not be read.
   */
  readonly ledger: bigint | null
  /** What the open items add up to. Known either way — a different resource. */
  readonly openItems: bigint
  readonly difference: bigint | null
  readonly outcome: ControlAccountOutcome
  readonly itemCount: number
  /**
   * Open items issued before the reconciliation year.
   *
   * The comparison is against **one** reporting year's movement on the control
   * account, and an open item has no year — a receivable raised in 2024 and
   * still unpaid is part of today's debtor position and contributes nothing to
   * 2026's movement. So any of these means a difference is expected, and
   * reading it as a finding about the administration would be wrong.
   */
  readonly itemsBeforeYear: number
}

/**
 * Where the trial balance came from, or why it did not.
 *
 * Three states, not two, and the third is the one that caught me out. A real
 * administration answered `financial/ReportingBalance` with **200 and no
 * rows** — readable, and empty. Treated as "read", an empty trial balance has
 * debit equal to credit, so it reported *balanced* on the strength of no
 * evidence, and then reported the whole debtor position as a difference
 * against a control account of zero: a confident €1.4M accusation assembled
 * entirely out of nothing.
 *
 * That is the same failure this type already guarded against for `unreadable`,
 * arriving through the door left open next to it. "Read and empty" makes no
 * claims either.
 */
export type TrialBalanceSource = 'read' | 'empty' | 'unreadable'

export interface TrialBalanceReconciliation {
  readonly year: number
  /**
   * `read` is the only value under which anything below is a claim. Every
   * total is null otherwise — an unread year is not an empty one, and an empty
   * year is not a balanced one.
   */
  readonly source: TrialBalanceSource
  readonly totalDebit: bigint | null
  readonly totalCredit: bigint | null
  readonly balanced: boolean | null
  readonly accountCount: number | null
  readonly transactionCount: number | null
  /** Codes with a balance in Exact and no account in the chart we read. */
  readonly orphanAccountCodes: readonly string[]
  readonly receivable: ControlAccountCheck
  readonly payable: ControlAccountCheck
}

export interface ExactImportPlan {
  readonly division: ExactDivision
  readonly currency: string
  readonly accounts: readonly ExactPlannedAccount[]
  readonly contacts: readonly ExactPlannedContact[]
  readonly openItems: readonly ExactPlannedOpenItem[]
  readonly taxCodes: readonly ExactPlannedTaxCode[]
  readonly documents: readonly ExactPlannedDocument[]
  readonly reconciliation: TrialBalanceReconciliation
  readonly warnings: readonly ExactProblem[]
  readonly problems: readonly ExactProblem[]
}

// ---------------------------------------------------------------------------
// Planning
// ---------------------------------------------------------------------------

/**
 * The resources without which there is no import.
 *
 * Everything else degrades: a division whose VAT codes are refused imports its
 * accounts without defaults, and one whose trial balance is refused imports
 * exactly the same data with no reconciliation behind it. These four are the
 * data itself.
 */
const REQUIRED_RESOURCES: ReadonlySet<string> = new Set([
  'bulk/Financial/GLAccounts',
  'bulk/CRM/Accounts',
  'read/financial/ReceivablesList',
  'read/financial/PayablesList',
])

/** What losing each optional resource actually costs, in the report. */
const CONSEQUENCE: Readonly<Record<string, string>> = {
  'financial/ReportingBalance':
    'The open items cannot be reconciled against the control accounts, so the import is not proved complete — it is still importable, but nothing here confirms the debtor and creditor positions add up.',
  'vat/VATCodes': 'Accounts are imported without their default VAT code.',
  'cashflow/PaymentConditions':
    'Contacts are imported on the default payment term rather than their own, so due dates will differ.',
  'bulk/Documents/Documents': 'No documents are imported.',
  'bulk/Documents/DocumentAttachments': 'Documents are imported without their files.',
}

/** Exact's own types for the two control accounts. */
const RECEIVABLE_TYPES = new Set([20, 21])
const PAYABLE_TYPES = new Set([22])

/** Exact stores a VAT percentage as a fraction. 0.21 becomes "21". */
function percentageText(fraction: number): string {
  const percent = fraction * 100
  const rounded = Math.round(percent * 100) / 100
  return String(rounded)
}

function appliesTo(code: ExactVatCode): ExactPlannedTaxCode['appliesTo'] {
  switch (code.transactionType) {
    case 'B':
      return 'both'
    case 'P':
      return 'purchase'
    case 'S':
      return 'sales'
    default:
      return 'unknown'
  }
}

/**
 * Days from an Exact payment condition.
 *
 * `PaymentEndOfMonths` is the one that does not fit: "end of the month plus
 * thirty days" is not a number of days, and turning it into one would move
 * every due date by up to a month depending on when the invoice was raised. The
 * number of days is taken and the fact is reported.
 */
function termsFor(
  code: string | null,
  conditions: ReadonlyMap<string, ExactPaymentCondition>,
  fallback: number,
): { readonly days: number; readonly approximated: ExactPaymentCondition | null } {
  if (code === null) return { days: fallback, approximated: null }
  const condition = conditions.get(code)
  if (condition === undefined) return { days: fallback, approximated: null }

  const days = Math.min(365, Math.max(0, condition.paymentDays))
  return { days, approximated: condition.paymentEndOfMonths > 0 ? condition : null }
}

const DEFAULT_TERMS_DAYS = 30

export function planExactImport(
  snapshot: ExactSnapshot,
  options: ExactImportOptions,
): ExactImportPlan {
  const problems: ExactProblem[] = []
  const warnings: ExactProblem[] = []

  const existingAccounts = new Set(options.existingAccountNumbers)
  const existingContacts = new Set(options.existingContactNumbers)
  const existingTaxCodes = new Set(options.existingTaxCodes)

  // The division's currency against ours. A division kept in another currency
  // is not something to convert on the way in — the amounts would be as at some
  // rate nobody chose — so it is a refusal with the reason named.
  if (snapshot.division.currency === null) {
    // Taken as ours, because the open items carry their own currency and are
    // each checked below. But said out loud: `ReportingBalance` has no currency
    // column at all, so an unstated division currency means the whole trial
    // balance is being read as ours on an assumption.
    warnings.push(
      problem(
        'unknown_currency',
        'division.currency',
        `Exact did not say which currency this administration is kept in. The trial balance is being read as ${options.currency}.`,
      ),
    )
  } else if (snapshot.division.currency !== options.currency) {
    problems.push(
      problem(
        'unknown_currency',
        'division.currency',
        `This administration is kept in ${snapshot.division.currency} and these books are in ${options.currency}. Importing would convert every amount at a rate nobody has chosen.`,
      ),
    )
  }

  // A caution on the chosen division is a warning rather than a refusal: an
  // accountant restoring an archived year means it. It has to be in the report.
  for (const caution of cautionsOf(snapshot.division)) {
    warnings.push(
      problem(
        'division_caution',
        'division',
        `${snapshot.division.description} (${String(snapshot.division.code)}) is ${caution}.`,
      ),
    )
  }

  // --- chart of accounts ---------------------------------------------------

  const seenNumbers = new Set<string>()
  const accounts: ExactPlannedAccount[] = []

  for (const account of snapshot.glAccounts) {
    if (seenNumbers.has(account.code)) {
      problems.push(
        problem(
          'account_number_collision',
          `accounts.${account.code}`,
          `Exact returned ${account.code} twice.`,
        ),
      )
      continue
    }
    seenNumbers.add(account.code)

    const classified = classifyAccount(account)
    if (classified.derived) {
      warnings.push(
        problem(
          'derived_account_type',
          `accounts.${account.code}`,
          `${account.code} (${account.description}) has Exact type ${String(account.type ?? 'none')}; it is being read as ${classified.type}/${classified.normalBalance} from its balance type and side. Check it before posting to it.`,
        ),
      )
    }

    if (account.vatCode !== null && !existingTaxCodes.has(account.vatCode)) {
      warnings.push(
        problem(
          'unknown_tax_code',
          `accounts.${account.code}.defaultTaxCode`,
          `${account.code} defaults to VAT code ${account.vatCode}, which does not exist here. The account is imported without a default.`,
        ),
      )
    }

    accounts.push({
      number: account.code,
      name: account.description,
      type: classified.type,
      normalBalance: classified.normalBalance,
      isBlocked: account.isBlocked,
      defaultTaxCode:
        account.vatCode !== null && existingTaxCodes.has(account.vatCode) ? account.vatCode : null,
      reportingCode: account.reportingCode,
      exists: existingAccounts.has(account.code),
      derived: classified.derived,
      exactType: account.type,
      exactTypeDescription: account.typeDescription,
    })
  }

  // --- tax codes -----------------------------------------------------------

  const taxCodes: ExactPlannedTaxCode[] = snapshot.vatCodes
    .filter((code) => !code.isBlocked)
    .map((code) => ({
      code: code.code,
      description: code.description,
      percentage: percentageText(code.percentage),
      appliesTo: appliesTo(code),
      reverseCharge: code.charged,
      mapped: existingTaxCodes.has(code.code),
    }))

  // --- contacts ------------------------------------------------------------

  const conditions = new Map(
    snapshot.paymentConditions.map((condition) => [condition.code, condition]),
  )
  const contactNumberByExactId = new Map<string, string>()
  const seenContactNumbers = new Set<string>()
  const contacts: ExactPlannedContact[] = []

  for (const account of snapshot.accounts) {
    // Type 'D' is one of the user's own divisions appearing as a relation. It is
    // not a customer or a supplier and importing it would create a contact for
    // the company itself.
    if (account.type === 'D') continue

    const roles = rolesFor(account)
    const country = (account.country ?? 'NL').toUpperCase().slice(0, 2)

    if (seenContactNumbers.has(account.code)) {
      problems.push(
        problem(
          'contact_number_collision',
          `contacts.${account.code}`,
          `Exact returned relation code ${account.code} twice (${account.name}).`,
        ),
      )
      continue
    }
    seenContactNumbers.add(account.code)
    contactNumberByExactId.set(account.id, account.code)

    const terms = termsFor(
      roles.isCustomer ? account.paymentConditionSales : account.paymentConditionPurchase,
      conditions,
      DEFAULT_TERMS_DAYS,
    )
    if (terms.approximated !== null) {
      warnings.push(
        problem(
          'payment_term_not_representable',
          `contacts.${account.code}.paymentTermsDays`,
          `${account.name} is on payment condition ${terms.approximated.code} (${terms.approximated.description}), which counts ${String(terms.approximated.paymentEndOfMonths)} month-ending(s). Imported as ${String(terms.days)} days, so due dates will differ.`,
        ),
      )
    }

    const hasAddress =
      account.addressLine1 !== null || account.postcode !== null || account.city !== null

    contacts.push({
      number: account.code,
      name: account.name,
      isCustomer: roles.isCustomer,
      isSupplier: roles.isSupplier,
      vatNumber: account.vatNumber,
      kvkNumber: account.chamberOfCommerce,
      countryCode: country,
      email: account.email,
      phone: account.phone,
      paymentTermsDays: terms.days,
      isBlocked: account.blocked,
      address: hasAddress
        ? {
            line1: account.addressLine1,
            line2: account.addressLine2,
            postcode: account.postcode,
            city: account.city,
            countryCode: country,
          }
        : null,
      exists: existingContacts.has(account.code),
      externalId: account.id,
    })
  }

  // --- open items ----------------------------------------------------------

  const openItems: ExactPlannedOpenItem[] = []
  const contactsByNumber = new Map(contacts.map((contact) => [contact.number, contact]))
  const forcedRoles = new Map<string, { customer: boolean; supplier: boolean }>()

  const collect = (items: readonly ExactOpenItem[], side: 'receivable' | 'payable'): void => {
    for (const item of items) {
      if (item.currency !== options.currency) {
        problems.push(
          problem(
            'unknown_currency',
            `openItems.${side}.${item.invoiceNumber}`,
            `${item.accountName} ${item.invoiceNumber} is in ${item.currency}, not ${options.currency}.`,
          ),
        )
        continue
      }

      // An open item for a relation Exact did not return as an account. Rare,
      // and it happens when a relation is deleted while an item is still open.
      // The item is what matters, so the contact is created from it.
      if (!contactsByNumber.has(item.accountCode)) {
        warnings.push(
          problem(
            'contact_number_collision',
            `openItems.${side}.${item.invoiceNumber}`,
            `${item.accountName} (${item.accountCode}) has an open item but was not returned as a relation. A contact is created from the open item.`,
          ),
        )
      }

      const forced = forcedRoles.get(item.accountCode) ?? { customer: false, supplier: false }
      if (side === 'receivable') forced.customer = true
      else forced.supplier = true
      forcedRoles.set(item.accountCode, forced)

      openItems.push({
        side,
        contactNumber: item.accountCode,
        contactName: item.accountName,
        documentNumber: item.invoiceNumber,
        issuedOn: item.invoiceDate,
        dueOn: item.dueDate,
        outstanding: item.outstanding,
        currency: item.currency,
        description: item.description,
        theirReference: item.yourRef,
        externalId: item.hid,
      })
    }
  }

  collect(snapshot.receivables, 'receivable')
  collect(snapshot.payables, 'payable')

  // A relation with an open receivable is a customer whatever Exact's `Status`
  // says, and one with an open payable is a supplier. Otherwise the open item
  // would arrive for a contact that cannot hold it.
  const withRoles: ExactPlannedContact[] = contacts.map((contact) => {
    const forced = forcedRoles.get(contact.number)
    if (forced === undefined) return contact
    return {
      ...contact,
      isCustomer: contact.isCustomer || forced.customer,
      isSupplier: contact.isSupplier || forced.supplier,
    }
  })

  // ...and one that Exact did not return at all is created from the item.
  for (const [number, forced] of forcedRoles) {
    if (contactsByNumber.has(number)) continue
    const item = openItems.find((candidate) => candidate.contactNumber === number)
    withRoles.push({
      number,
      name: item?.contactName ?? number,
      isCustomer: forced.customer,
      isSupplier: forced.supplier,
      vatNumber: null,
      kvkNumber: null,
      countryCode: 'NL',
      email: null,
      phone: null,
      paymentTermsDays: DEFAULT_TERMS_DAYS,
      isBlocked: false,
      address: null,
      exists: existingContacts.has(number),
      externalId: '',
    })
  }

  // --- documents -----------------------------------------------------------

  const attachmentsByDocument = new Map<string, ExactAttachment[]>()
  for (const attachment of snapshot.attachments) {
    if (attachment.url === null) {
      warnings.push(
        problem(
          'attachment_without_url',
          `documents.${attachment.documentId}`,
          `${attachment.fileName} has no download URL in Exact and cannot be fetched.`,
        ),
      )
      continue
    }
    const list = attachmentsByDocument.get(attachment.documentId) ?? []
    list.push(attachment)
    attachmentsByDocument.set(attachment.documentId, list)
  }

  const documents: ExactPlannedDocument[] = snapshot.documents.map((document) => ({
    externalId: document.id,
    subject: document.subject,
    documentDate: document.documentDate,
    contactNumber: document.accountCode,
    typeDescription: document.typeDescription,
    attachments: (attachmentsByDocument.get(document.id) ?? []).map((attachment) => ({
      externalId: attachment.id,
      fileName: attachment.fileName,
      fileSize: attachment.fileSize,
      // Non-null by construction: the null case was filtered above.
      url: attachment.url ?? '',
    })),
  }))

  // --- the reconciliation --------------------------------------------------

  // Anything the read pass was refused, before the reconciliation is read —
  // because what it could not see is why the reconciliation says what it says.
  for (const missing of snapshot.unreadable) {
    const required = REQUIRED_RESOURCES.has(missing.resource)
    const rights = missing.status === 403 ? diagnose(missing) : ''

    ;(required ? problems : warnings).push(
      problem(
        'resource_unreadable',
        `resources.${missing.resource}`,
        `${missing.resource} could not be read (${String(missing.status)}).${rights}${
          required
            ? ' The import needs it.'
            : ` ${CONSEQUENCE[missing.resource] ?? 'It is imported without that data.'}`
        }`,
      ),
    )
  }

  const reconciliation = reconcile(snapshot, accounts, openItems, options)
  if (reconciliation.source === 'read' && reconciliation.balanced === false) {
    problems.push(
      problem(
        'trial_balance_unbalanced',
        'reconciliation',
        `Exact's own trial balance for ${String(snapshot.year)} does not balance: ${reconciliation.totalDebit?.toString() ?? '?'} debit against ${reconciliation.totalCredit?.toString() ?? '?'} credit. Nothing downstream of that is safe to import.`,
      ),
    )
  }
  if (reconciliation.source === 'empty') {
    warnings.push(
      problem(
        'trial_balance_empty',
        'reconciliation',
        `Exact returned no summarised balances at all for ${String(snapshot.year)}, so there was nothing to reconcile the open items against. The administration may have no postings in that year, or the rights that allow the call may still be filtering every row out of it. The import is unaffected; what is missing is the proof.`,
      ),
    )
  }
  for (const code of reconciliation.orphanAccountCodes) {
    warnings.push(
      problem(
        'trial_balance_account_missing',
        `reconciliation.accounts.${code}`,
        `${code} has a balance in Exact but is not in the chart of accounts it returned.`,
      ),
    )
  }
  for (const check of [reconciliation.receivable, reconciliation.payable]) {
    // `not_reconciled` is deliberately silent here: the unreadable resource
    // above already said why, and saying it twice per side is three warnings
    // for one cause.
    if (check.outcome === 'no_control_account') {
      warnings.push(
        problem(
          'no_control_account',
          `reconciliation.${check.side}`,
          `No ${check.side === 'receivable' ? 'debtors' : 'creditors'} control account was found in Exact's chart, so the open items could not be reconciled against one.`,
        ),
      )
    } else if (check.outcome === 'differs') {
      // Two very different sentences. A difference on an administration whose
      // open items all fall inside the year is a finding about their books. A
      // difference where some are older is mostly an artefact of comparing an
      // all-ages position against one year's movement, and saying "something is
      // booked without an open item behind it" would be an accusation the data
      // does not support.
      const stated =
        check.itemsBeforeYear > 0
          ? `${String(check.itemsBeforeYear)} of the ${String(check.itemCount)} ${check.side} open items were issued before ${String(reconciliation.year)}, and this compares them against that year's movement alone. Expect a difference; it is the question, not the answer. Reconciling an administration with history needs the control account's cumulative balance, which this does not yet read.`
          : 'Something is booked to the control account without an open item behind it.'

      warnings.push(
        problem(
          'open_items_do_not_reconcile',
          `reconciliation.${check.side}`,
          `The ${check.side} open items total ${check.openItems.toString()} against ${check.ledger?.toString() ?? '?'} on ${check.accountCodes.join(', ')} — a difference of ${check.difference?.toString() ?? '?'}. ${stated}`,
        ),
      )
    }
  }

  return {
    division: snapshot.division,
    currency: options.currency,
    accounts,
    contacts: withRoles,
    openItems,
    taxCodes,
    documents,
    reconciliation,
    warnings,
    problems,
  }
}

/** The same cautions `describeDivision` reports, as text for a warning. */
function cautionsOf(division: ExactDivision): readonly string[] {
  const cautions: string[] = []
  if (division.isPracticeDivision) cautions.push('a practice division')
  if (division.isDossierDivision) cautions.push('a dossier division')
  if (division.status === 2 || division.archiveDate !== null) cautions.push('archived')
  else if (division.status === 0) cautions.push('inactive')
  return cautions
}

function reconcile(
  snapshot: ExactSnapshot,
  accounts: readonly ExactPlannedAccount[],
  openItems: readonly ExactPlannedOpenItem[],
  options: ExactImportOptions,
): TrialBalanceReconciliation {
  const controlCodes = (
    override: readonly string[] | undefined,
    types: ReadonlySet<number>,
  ): readonly string[] =>
    override ??
    snapshot.glAccounts
      .filter((account) => account.type !== null && types.has(account.type))
      .map((account) => account.code)
      .sort()

  const receivableCodes = controlCodes(options.receivableAccountCodes, RECEIVABLE_TYPES)
  const payableCodes = controlCodes(options.payableAccountCodes, PAYABLE_TYPES)

  const yearStart = `${String(snapshot.year)}-01-01`

  const totalFor = (
    side: 'receivable' | 'payable',
  ): { total: bigint; count: number; before: number } => {
    const items = openItems.filter((item) => item.side === side)
    return {
      total: items.reduce((sum, item) => sum + item.outstanding, 0n),
      count: items.length,
      before: items.filter((item) => item.issuedOn < yearStart).length,
    }
  }

  // Nothing to compare against, so nothing is claimed. The open-item totals
  // are still reported — they come from a different resource and are still
  // true — but they are not measured against a control account of zero and the
  // shortfall called a difference.
  //
  // `length === 0` matters as much as `null`. A division that answers 200 with
  // no rows is readable and empty, and an empty trial balance balances: taking
  // it at face value reported a €1.4M discrepancy in books nobody had looked
  // at.
  if (snapshot.trialBalance === null || snapshot.trialBalance.length === 0) {
    const unreconciled = (
      side: 'receivable' | 'payable',
      codes: readonly string[],
    ): ControlAccountCheck => {
      const { total, count, before } = totalFor(side)
      return {
        side,
        accountCodes: codes,
        ledger: null,
        openItems: total,
        difference: null,
        outcome: 'not_reconciled',
        itemCount: count,
        itemsBeforeYear: before,
      }
    }

    return {
      year: snapshot.year,
      source: snapshot.trialBalance === null ? 'unreadable' : 'empty',
      totalDebit: null,
      totalCredit: null,
      balanced: null,
      accountCount: null,
      transactionCount: null,
      orphanAccountCodes: [],
      receivable: unreconciled('receivable', receivableCodes),
      payable: unreconciled('payable', payableCodes),
    }
  }

  let totalDebit = 0n
  let totalCredit = 0n
  let transactionCount = 0
  const perAccount = new Map<string, bigint>()

  for (const row of snapshot.trialBalance) {
    totalDebit += row.debit
    totalCredit += row.credit
    transactionCount += row.transactions
    // Signed debit-minus-credit, summed across every period of the year.
    const running = perAccount.get(row.accountCode) ?? 0n
    perAccount.set(row.accountCode, running + row.debit - row.credit)
  }

  const chartCodes = new Set(accounts.map((account) => account.number))
  const orphanAccountCodes = [...perAccount.keys()].filter((code) => !chartCodes.has(code)).sort()

  const check = (side: 'receivable' | 'payable', codes: readonly string[]): ControlAccountCheck => {
    // Debtors are a debit balance and creditors a credit one, so each side is
    // measured in its own direction and compared as a positive amount. Comparing
    // signed totals would make a correct creditors position look like a
    // difference of twice its value.
    const signed = codes.reduce((total, code) => total + (perAccount.get(code) ?? 0n), 0n)
    const ledger = side === 'receivable' ? signed : -signed
    const { total, count, before } = totalFor(side)

    return {
      side,
      accountCodes: codes,
      itemsBeforeYear: before,
      ledger,
      openItems: total,
      difference: total - ledger,
      outcome: codes.length === 0 ? 'no_control_account' : total === ledger ? 'matches' : 'differs',
      itemCount: count,
    }
  }

  return {
    year: snapshot.year,
    source: 'read',
    totalDebit,
    totalCredit,
    balanced: totalDebit === totalCredit,
    accountCount: perAccount.size,
    transactionCount,
    orphanAccountCodes,
    receivable: check('receivable', receivableCodes),
    payable: check('payable', payableCodes),
  }
}
