import type { AccountType } from '../ledger/types.js'
import type { ExactDivision } from '../ports/exact.js'
import {
  classifyAccount,
  rolesFor,
  type ExactAccount,
  type ExactAttachment,
  type ExactDocument,
  type ExactGLAccount,
  type ExactOpenItem,
  type ExactPaymentCondition,
  type ExactReportingBalance,
  type ExactVatCode,
} from './resources.js'

/**
 * What importing an Exact division would do, before it does it (spec 13).
 *
 * "A dry-run mode producing a reconciliation report against the source
 * system's trial balance before anything is committed."
 *
 * That sentence is the whole design of this module. The plan is a pure function
 * of what was read from Exact and what already exists here — no database, no
 * clock, no network — so the report a human approves is exactly the thing that
 * gets executed, rather than a preview generated by a second code path that
 * might disagree with the first.
 *
 * ## What is reconciled, and why it is these three things
 *
 * The Exact importer brings master data and open items across, not history —
 * history is what the XAF import is for. So there is no set of postings to
 * compare against a trial balance line by line. What there is, and what an
 * accountant would actually ask for, is three questions:
 *
 * 1. **Does Exact's own trial balance balance?** If debit and credit do not
 *    agree in the source, nothing downstream of it can be trusted, and finding
 *    that out after the import is finding it out too late.
 * 2. **Do the open items add up to the control accounts?** Exact's receivables
 *    list should total to what its debtors account holds, and the payables list
 *    to its creditors account. When they agree, the open items we are about to
 *    import are provably the complete debtor and creditor position. When they
 *    do not, something in Exact is booked to the control account without an
 *    open item behind it, and importing the list would start us short.
 * 3. **Is every account the trial balance mentions in the chart we are
 *    importing?** A code with a balance and no account is a line that would
 *    have nowhere to land.
 *
 * The first is a `problem`. The other two are reported as differences with
 * their amounts, because a real migration often has a known and explicable one
 * — and refusing to proceed on a two-cent rounding difference in a
 * twelve-year-old administration would make the tool useless. What it must not
 * do is fail to mention it.
 */

/** Something wrong with what Exact returned, or with what it would mean here. */
export type ExactProblemCode =
  | 'trial_balance_unbalanced'
  | 'trial_balance_account_missing'
  | 'open_items_do_not_reconcile'
  | 'no_control_account'
  | 'account_number_collision'
  | 'contact_number_collision'
  | 'unknown_currency'
  | 'derived_account_type'
  | 'unknown_tax_code'
  | 'payment_term_not_representable'
  | 'attachment_without_url'
  | 'division_caution'

export interface ExactProblem {
  readonly code: ExactProblemCode
  readonly path: string | null
  readonly message: string
}

function problem(code: ExactProblemCode, path: string | null, message: string): ExactProblem {
  return { code, path, message }
}

// ---------------------------------------------------------------------------
// What was read
// ---------------------------------------------------------------------------

/**
 * Everything one division-scoped read pass collected.
 *
 * A snapshot rather than a client, so that planning is testable from a fixture
 * and a plan can be shown, stored and re-shown without asking Exact again.
 */
export interface ExactSnapshot {
  readonly division: ExactDivision
  readonly glAccounts: readonly ExactGLAccount[]
  readonly vatCodes: readonly ExactVatCode[]
  readonly accounts: readonly ExactAccount[]
  readonly paymentConditions: readonly ExactPaymentCondition[]
  readonly receivables: readonly ExactOpenItem[]
  readonly payables: readonly ExactOpenItem[]
  /** `financial/ReportingBalance` for one year, both statuses. */
  readonly trialBalance: readonly ExactReportingBalance[]
  readonly year: number
  readonly documents: readonly ExactDocument[]
  readonly attachments: readonly ExactAttachment[]
}

/** What this administration already has, so the plan can say new or existing. */
export interface ExactImportOptions {
  readonly entityId: string
  /** The entity's own currency. A division in another one is a problem. */
  readonly currency: string
  readonly existingAccountNumbers: readonly string[]
  readonly existingContactNumbers: readonly string[]
  readonly existingTaxCodes: readonly string[]
  /**
   * Exact's account types for the debtors and creditors control accounts: 20
   * and 22. Overridable because a division can have more than one of each, and
   * because a chart that was migrated into Exact from somewhere else sometimes
   * has them typed as `90 = General`.
   */
  readonly receivableAccountCodes?: readonly string[]
  readonly payableAccountCodes?: readonly string[]
}

// ---------------------------------------------------------------------------
// What the plan says
// ---------------------------------------------------------------------------

export interface ExactPlannedAccount {
  readonly number: string
  readonly name: string
  readonly type: AccountType
  readonly normalBalance: 'debit' | 'credit'
  readonly isBlocked: boolean
  readonly defaultTaxCode: string | null
  /** Exact's `ReportingCode`, which is sometimes an RGS code and sometimes not. */
  readonly reportingCode: string | null
  /** True when this number already exists here and would be left alone. */
  readonly exists: boolean
  /** True when the type came from `BalanceType`/`BalanceSide` rather than `Type`. */
  readonly derived: boolean
  readonly exactType: number | null
  readonly exactTypeDescription: string | null
}

export interface ExactPlannedContact {
  readonly number: string
  readonly name: string
  readonly isCustomer: boolean
  readonly isSupplier: boolean
  readonly vatNumber: string | null
  readonly kvkNumber: string | null
  readonly countryCode: string
  readonly email: string | null
  readonly phone: string | null
  readonly paymentTermsDays: number
  readonly isBlocked: boolean
  readonly address: {
    readonly line1: string | null
    readonly line2: string | null
    readonly postcode: string | null
    readonly city: string | null
    readonly countryCode: string
  } | null
  readonly exists: boolean
  /** Exact's GUID, kept so a re-import matches rather than duplicating. */
  readonly externalId: string
}

export interface ExactPlannedOpenItem {
  readonly side: 'receivable' | 'payable'
  readonly contactNumber: string
  readonly contactName: string
  /** The number the invoice carries in Exact, preserved. */
  readonly documentNumber: string
  readonly issuedOn: string
  readonly dueOn: string
  readonly outstanding: bigint
  readonly currency: string
  readonly description: string | null
  readonly theirReference: string | null
  readonly externalId: string
}

export interface ExactPlannedDocument {
  readonly externalId: string
  readonly subject: string
  readonly documentDate: string | null
  readonly contactNumber: string | null
  readonly typeDescription: string | null
  readonly attachments: readonly {
    readonly externalId: string
    readonly fileName: string
    readonly fileSize: number
    readonly url: string
  }[]
}

export interface ExactPlannedTaxCode {
  readonly code: string
  readonly description: string
  /** As a percentage, not Exact's fraction: 21 rather than 0.21. */
  readonly percentage: string
  readonly appliesTo: 'both' | 'purchase' | 'sales' | 'unknown'
  readonly reverseCharge: boolean
  /** True when a code of this name already exists here. */
  readonly mapped: boolean
}

/** One side of the open-items reconciliation. */
export interface ControlAccountCheck {
  readonly side: 'receivable' | 'payable'
  /** The account codes in Exact this side was measured against. */
  readonly accountCodes: readonly string[]
  /** What the trial balance says those accounts hold, as a positive amount. */
  readonly ledger: bigint
  /** What the open items add up to. */
  readonly openItems: bigint
  readonly difference: bigint
  readonly matches: boolean
  readonly itemCount: number
}

export interface TrialBalanceReconciliation {
  readonly year: number
  readonly totalDebit: bigint
  readonly totalCredit: bigint
  readonly balanced: boolean
  readonly accountCount: number
  readonly transactionCount: number
  /** Codes with a balance in Exact and no account in the chart we read. */
  readonly orphanAccountCodes: readonly string[]
  readonly receivable: ControlAccountCheck
  readonly payable: ControlAccountCheck
}

export interface ExactImportPlan {
  readonly division: ExactDivision
  readonly currency: string
  readonly accounts: readonly ExactPlannedAccount[]
  readonly contacts: readonly ExactPlannedContact[]
  readonly openItems: readonly ExactPlannedOpenItem[]
  readonly taxCodes: readonly ExactPlannedTaxCode[]
  readonly documents: readonly ExactPlannedDocument[]
  readonly reconciliation: TrialBalanceReconciliation
  readonly warnings: readonly ExactProblem[]
  readonly problems: readonly ExactProblem[]
}

// ---------------------------------------------------------------------------
// Planning
// ---------------------------------------------------------------------------

/** Exact's own types for the two control accounts. */
const RECEIVABLE_TYPES = new Set([20, 21])
const PAYABLE_TYPES = new Set([22])

/** Exact stores a VAT percentage as a fraction. 0.21 becomes "21". */
function percentageText(fraction: number): string {
  const percent = fraction * 100
  const rounded = Math.round(percent * 100) / 100
  return String(rounded)
}

function appliesTo(code: ExactVatCode): ExactPlannedTaxCode['appliesTo'] {
  switch (code.transactionType) {
    case 'B':
      return 'both'
    case 'P':
      return 'purchase'
    case 'S':
      return 'sales'
    default:
      return 'unknown'
  }
}

/**
 * Days from an Exact payment condition.
 *
 * `PaymentEndOfMonths` is the one that does not fit: "end of the month plus
 * thirty days" is not a number of days, and turning it into one would move
 * every due date by up to a month depending on when the invoice was raised. The
 * number of days is taken and the fact is reported.
 */
function termsFor(
  code: string | null,
  conditions: ReadonlyMap<string, ExactPaymentCondition>,
  fallback: number,
): { readonly days: number; readonly approximated: ExactPaymentCondition | null } {
  if (code === null) return { days: fallback, approximated: null }
  const condition = conditions.get(code)
  if (condition === undefined) return { days: fallback, approximated: null }

  const days = Math.min(365, Math.max(0, condition.paymentDays))
  return { days, approximated: condition.paymentEndOfMonths > 0 ? condition : null }
}

const DEFAULT_TERMS_DAYS = 30

export function planExactImport(
  snapshot: ExactSnapshot,
  options: ExactImportOptions,
): ExactImportPlan {
  const problems: ExactProblem[] = []
  const warnings: ExactProblem[] = []

  const existingAccounts = new Set(options.existingAccountNumbers)
  const existingContacts = new Set(options.existingContactNumbers)
  const existingTaxCodes = new Set(options.existingTaxCodes)

  // The division's currency against ours. A division kept in another currency
  // is not something to convert on the way in — the amounts would be as at some
  // rate nobody chose — so it is a refusal with the reason named.
  if (snapshot.division.currency === null) {
    // Taken as ours, because the open items carry their own currency and are
    // each checked below. But said out loud: `ReportingBalance` has no currency
    // column at all, so an unstated division currency means the whole trial
    // balance is being read as ours on an assumption.
    warnings.push(
      problem(
        'unknown_currency',
        'division.currency',
        `Exact did not say which currency this administration is kept in. The trial balance is being read as ${options.currency}.`,
      ),
    )
  } else if (snapshot.division.currency !== options.currency) {
    problems.push(
      problem(
        'unknown_currency',
        'division.currency',
        `This administration is kept in ${snapshot.division.currency} and these books are in ${options.currency}. Importing would convert every amount at a rate nobody has chosen.`,
      ),
    )
  }

  // A caution on the chosen division is a warning rather than a refusal: an
  // accountant restoring an archived year means it. It has to be in the report.
  for (const caution of cautionsOf(snapshot.division)) {
    warnings.push(
      problem(
        'division_caution',
        'division',
        `${snapshot.division.description} (${String(snapshot.division.code)}) is ${caution}.`,
      ),
    )
  }

  // --- chart of accounts ---------------------------------------------------

  const seenNumbers = new Set<string>()
  const accounts: ExactPlannedAccount[] = []

  for (const account of snapshot.glAccounts) {
    if (seenNumbers.has(account.code)) {
      problems.push(
        problem(
          'account_number_collision',
          `accounts.${account.code}`,
          `Exact returned ${account.code} twice.`,
        ),
      )
      continue
    }
    seenNumbers.add(account.code)

    const classified = classifyAccount(account)
    if (classified.derived) {
      warnings.push(
        problem(
          'derived_account_type',
          `accounts.${account.code}`,
          `${account.code} (${account.description}) has Exact type ${String(account.type ?? 'none')}; it is being read as ${classified.type}/${classified.normalBalance} from its balance type and side. Check it before posting to it.`,
        ),
      )
    }

    if (account.vatCode !== null && !existingTaxCodes.has(account.vatCode)) {
      warnings.push(
        problem(
          'unknown_tax_code',
          `accounts.${account.code}.defaultTaxCode`,
          `${account.code} defaults to VAT code ${account.vatCode}, which does not exist here. The account is imported without a default.`,
        ),
      )
    }

    accounts.push({
      number: account.code,
      name: account.description,
      type: classified.type,
      normalBalance: classified.normalBalance,
      isBlocked: account.isBlocked,
      defaultTaxCode:
        account.vatCode !== null && existingTaxCodes.has(account.vatCode) ? account.vatCode : null,
      reportingCode: account.reportingCode,
      exists: existingAccounts.has(account.code),
      derived: classified.derived,
      exactType: account.type,
      exactTypeDescription: account.typeDescription,
    })
  }

  // --- tax codes -----------------------------------------------------------

  const taxCodes: ExactPlannedTaxCode[] = snapshot.vatCodes
    .filter((code) => !code.isBlocked)
    .map((code) => ({
      code: code.code,
      description: code.description,
      percentage: percentageText(code.percentage),
      appliesTo: appliesTo(code),
      reverseCharge: code.charged,
      mapped: existingTaxCodes.has(code.code),
    }))

  // --- contacts ------------------------------------------------------------

  const conditions = new Map(
    snapshot.paymentConditions.map((condition) => [condition.code, condition]),
  )
  const contactNumberByExactId = new Map<string, string>()
  const seenContactNumbers = new Set<string>()
  const contacts: ExactPlannedContact[] = []

  for (const account of snapshot.accounts) {
    // Type 'D' is one of the user's own divisions appearing as a relation. It is
    // not a customer or a supplier and importing it would create a contact for
    // the company itself.
    if (account.type === 'D') continue

    const roles = rolesFor(account)
    const country = (account.country ?? 'NL').toUpperCase().slice(0, 2)

    if (seenContactNumbers.has(account.code)) {
      problems.push(
        problem(
          'contact_number_collision',
          `contacts.${account.code}`,
          `Exact returned relation code ${account.code} twice (${account.name}).`,
        ),
      )
      continue
    }
    seenContactNumbers.add(account.code)
    contactNumberByExactId.set(account.id, account.code)

    const terms = termsFor(
      roles.isCustomer ? account.paymentConditionSales : account.paymentConditionPurchase,
      conditions,
      DEFAULT_TERMS_DAYS,
    )
    if (terms.approximated !== null) {
      warnings.push(
        problem(
          'payment_term_not_representable',
          `contacts.${account.code}.paymentTermsDays`,
          `${account.name} is on payment condition ${terms.approximated.code} (${terms.approximated.description}), which counts ${String(terms.approximated.paymentEndOfMonths)} month-ending(s). Imported as ${String(terms.days)} days, so due dates will differ.`,
        ),
      )
    }

    const hasAddress =
      account.addressLine1 !== null || account.postcode !== null || account.city !== null

    contacts.push({
      number: account.code,
      name: account.name,
      isCustomer: roles.isCustomer,
      isSupplier: roles.isSupplier,
      vatNumber: account.vatNumber,
      kvkNumber: account.chamberOfCommerce,
      countryCode: country,
      email: account.email,
      phone: account.phone,
      paymentTermsDays: terms.days,
      isBlocked: account.blocked,
      address: hasAddress
        ? {
            line1: account.addressLine1,
            line2: account.addressLine2,
            postcode: account.postcode,
            city: account.city,
            countryCode: country,
          }
        : null,
      exists: existingContacts.has(account.code),
      externalId: account.id,
    })
  }

  // --- open items ----------------------------------------------------------

  const openItems: ExactPlannedOpenItem[] = []
  const contactsByNumber = new Map(contacts.map((contact) => [contact.number, contact]))
  const forcedRoles = new Map<string, { customer: boolean; supplier: boolean }>()

  const collect = (items: readonly ExactOpenItem[], side: 'receivable' | 'payable'): void => {
    for (const item of items) {
      if (item.currency !== options.currency) {
        problems.push(
          problem(
            'unknown_currency',
            `openItems.${side}.${item.invoiceNumber}`,
            `${item.accountName} ${item.invoiceNumber} is in ${item.currency}, not ${options.currency}.`,
          ),
        )
        continue
      }

      // An open item for a relation Exact did not return as an account. Rare,
      // and it happens when a relation is deleted while an item is still open.
      // The item is what matters, so the contact is created from it.
      if (!contactsByNumber.has(item.accountCode)) {
        warnings.push(
          problem(
            'contact_number_collision',
            `openItems.${side}.${item.invoiceNumber}`,
            `${item.accountName} (${item.accountCode}) has an open item but was not returned as a relation. A contact is created from the open item.`,
          ),
        )
      }

      const forced = forcedRoles.get(item.accountCode) ?? { customer: false, supplier: false }
      if (side === 'receivable') forced.customer = true
      else forced.supplier = true
      forcedRoles.set(item.accountCode, forced)

      openItems.push({
        side,
        contactNumber: item.accountCode,
        contactName: item.accountName,
        documentNumber: item.invoiceNumber,
        issuedOn: item.invoiceDate,
        dueOn: item.dueDate,
        outstanding: item.outstanding,
        currency: item.currency,
        description: item.description,
        theirReference: item.yourRef,
        externalId: item.hid,
      })
    }
  }

  collect(snapshot.receivables, 'receivable')
  collect(snapshot.payables, 'payable')

  // A relation with an open receivable is a customer whatever Exact's `Status`
  // says, and one with an open payable is a supplier. Otherwise the open item
  // would arrive for a contact that cannot hold it.
  const withRoles: ExactPlannedContact[] = contacts.map((contact) => {
    const forced = forcedRoles.get(contact.number)
    if (forced === undefined) return contact
    return {
      ...contact,
      isCustomer: contact.isCustomer || forced.customer,
      isSupplier: contact.isSupplier || forced.supplier,
    }
  })

  // ...and one that Exact did not return at all is created from the item.
  for (const [number, forced] of forcedRoles) {
    if (contactsByNumber.has(number)) continue
    const item = openItems.find((candidate) => candidate.contactNumber === number)
    withRoles.push({
      number,
      name: item?.contactName ?? number,
      isCustomer: forced.customer,
      isSupplier: forced.supplier,
      vatNumber: null,
      kvkNumber: null,
      countryCode: 'NL',
      email: null,
      phone: null,
      paymentTermsDays: DEFAULT_TERMS_DAYS,
      isBlocked: false,
      address: null,
      exists: existingContacts.has(number),
      externalId: '',
    })
  }

  // --- documents -----------------------------------------------------------

  const attachmentsByDocument = new Map<string, ExactAttachment[]>()
  for (const attachment of snapshot.attachments) {
    if (attachment.url === null) {
      warnings.push(
        problem(
          'attachment_without_url',
          `documents.${attachment.documentId}`,
          `${attachment.fileName} has no download URL in Exact and cannot be fetched.`,
        ),
      )
      continue
    }
    const list = attachmentsByDocument.get(attachment.documentId) ?? []
    list.push(attachment)
    attachmentsByDocument.set(attachment.documentId, list)
  }

  const documents: ExactPlannedDocument[] = snapshot.documents.map((document) => ({
    externalId: document.id,
    subject: document.subject,
    documentDate: document.documentDate,
    contactNumber: document.accountCode,
    typeDescription: document.typeDescription,
    attachments: (attachmentsByDocument.get(document.id) ?? []).map((attachment) => ({
      externalId: attachment.id,
      fileName: attachment.fileName,
      fileSize: attachment.fileSize,
      // Non-null by construction: the null case was filtered above.
      url: attachment.url ?? '',
    })),
  }))

  // --- the reconciliation --------------------------------------------------

  const reconciliation = reconcile(snapshot, accounts, openItems, options)
  if (!reconciliation.balanced) {
    problems.push(
      problem(
        'trial_balance_unbalanced',
        'reconciliation',
        `Exact's own trial balance for ${String(snapshot.year)} does not balance: ${reconciliation.totalDebit.toString()} debit against ${reconciliation.totalCredit.toString()} credit. Nothing downstream of that is safe to import.`,
      ),
    )
  }
  for (const code of reconciliation.orphanAccountCodes) {
    warnings.push(
      problem(
        'trial_balance_account_missing',
        `reconciliation.accounts.${code}`,
        `${code} has a balance in Exact but is not in the chart of accounts it returned.`,
      ),
    )
  }
  for (const check of [reconciliation.receivable, reconciliation.payable]) {
    if (check.accountCodes.length === 0) {
      warnings.push(
        problem(
          'no_control_account',
          `reconciliation.${check.side}`,
          `No ${check.side === 'receivable' ? 'debtors' : 'creditors'} control account was found in Exact's chart, so the open items could not be reconciled against one.`,
        ),
      )
    } else if (!check.matches) {
      warnings.push(
        problem(
          'open_items_do_not_reconcile',
          `reconciliation.${check.side}`,
          `The ${check.side} open items total ${check.openItems.toString()} against ${check.ledger.toString()} on ${check.accountCodes.join(', ')} — a difference of ${check.difference.toString()}. Something is booked to the control account without an open item behind it.`,
        ),
      )
    }
  }

  return {
    division: snapshot.division,
    currency: options.currency,
    accounts,
    contacts: withRoles,
    openItems,
    taxCodes,
    documents,
    reconciliation,
    warnings,
    problems,
  }
}

/** The same cautions `describeDivision` reports, as text for a warning. */
function cautionsOf(division: ExactDivision): readonly string[] {
  const cautions: string[] = []
  if (division.isPracticeDivision) cautions.push('a practice division')
  if (division.isDossierDivision) cautions.push('a dossier division')
  if (division.status === 2 || division.archiveDate !== null) cautions.push('archived')
  else if (division.status === 0) cautions.push('inactive')
  return cautions
}

function reconcile(
  snapshot: ExactSnapshot,
  accounts: readonly ExactPlannedAccount[],
  openItems: readonly ExactPlannedOpenItem[],
  options: ExactImportOptions,
): TrialBalanceReconciliation {
  let totalDebit = 0n
  let totalCredit = 0n
  let transactionCount = 0
  const perAccount = new Map<string, bigint>()

  for (const row of snapshot.trialBalance) {
    totalDebit += row.debit
    totalCredit += row.credit
    transactionCount += row.transactions
    // Signed debit-minus-credit, summed across every period of the year.
    const running = perAccount.get(row.accountCode) ?? 0n
    perAccount.set(row.accountCode, running + row.debit - row.credit)
  }

  const chartCodes = new Set(accounts.map((account) => account.number))
  const orphanAccountCodes = [...perAccount.keys()].filter((code) => !chartCodes.has(code)).sort()

  const controlCodes = (
    override: readonly string[] | undefined,
    types: ReadonlySet<number>,
  ): readonly string[] =>
    override ??
    snapshot.glAccounts
      .filter((account) => account.type !== null && types.has(account.type))
      .map((account) => account.code)
      .sort()

  const check = (side: 'receivable' | 'payable', codes: readonly string[]): ControlAccountCheck => {
    // Debtors are a debit balance and creditors a credit one, so each side is
    // measured in its own direction and compared as a positive amount. Comparing
    // signed totals would make a correct creditors position look like a
    // difference of twice its value.
    const signed = codes.reduce((total, code) => total + (perAccount.get(code) ?? 0n), 0n)
    const ledger = side === 'receivable' ? signed : -signed

    const items = openItems.filter((item) => item.side === side)
    const total = items.reduce((sum, item) => sum + item.outstanding, 0n)

    return {
      side,
      accountCodes: codes,
      ledger,
      openItems: total,
      difference: total - ledger,
      matches: codes.length > 0 && total === ledger,
      itemCount: items.length,
    }
  }

  return {
    year: snapshot.year,
    totalDebit,
    totalCredit,
    balanced: totalDebit === totalCredit,
    accountCount: perAccount.size,
    transactionCount,
    orphanAccountCodes,
    receivable: check('receivable', controlCodes(options.receivableAccountCodes, RECEIVABLE_TYPES)),
    payable: check('payable', controlCodes(options.payableAccountCodes, PAYABLE_TYPES)),
  }
}
